import sqlite3
import sys
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtWidgets
import NextOffice.shipment.shipment_main
import NextOffice.shipment.shipment_edit
import NextOffice.shipment.shipment_add

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1311, 809)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(540, 10, 161, 31))
        self.label_13.setObjectName("label_13")
        self.label_id1 = QtWidgets.QLabel(Form)
        self.label_id1.setGeometry(QtCore.QRect(120, 60, 91, 21))
        self.label_id1.setObjectName("label_id1")
        self.lineEdit_search = QtWidgets.QLineEdit(Form)
        self.lineEdit_search.setGeometry(QtCore.QRect(160, 10, 113, 20))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.label_customer1 = QtWidgets.QLabel(Form)
        self.label_customer1.setGeometry(QtCore.QRect(90, 130, 161, 21))
        self.label_customer1.setObjectName("label_customer1")
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(10, 80, 251, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.pushButton_SwitchCustomer = QtWidgets.QPushButton(Form)
        self.pushButton_SwitchCustomer.setGeometry(QtCore.QRect(1170, 10, 91, 23))
        self.pushButton_SwitchCustomer.setObjectName("pushButton_SwitchCustomer")
        self.pushButton_edit1 = QtWidgets.QPushButton(Form)
        self.pushButton_edit1.setGeometry(QtCore.QRect(10, 710, 71, 23))
        self.pushButton_edit1.setObjectName("pushButton_edit1")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 61, 39))
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 40, 1291, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_SwitchService = QtWidgets.QPushButton(Form)
        self.pushButton_SwitchService.setGeometry(QtCore.QRect(1070, 10, 91, 23))
        self.pushButton_SwitchService.setObjectName("pushButton_SwitchService")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(130, 12, 31, 20))
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 61, 39))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 61, 39))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 240, 61, 39))
        self.label_3.setObjectName("label_3")
        self.pushButton_previous = QtWidgets.QPushButton(Form)
        self.pushButton_previous.setGeometry(QtCore.QRect(120, 770, 75, 23))
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.pushButton_next = QtWidgets.QPushButton(Form)
        self.pushButton_next.setGeometry(QtCore.QRect(230, 770, 75, 23))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_new = QtWidgets.QPushButton(Form)
        self.pushButton_new.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.pushButton_new.setObjectName("pushButton_new")
        self.lineEdit_jump = QtWidgets.QLineEdit(Form)
        self.lineEdit_jump.setGeometry(QtCore.QRect(560, 770, 31, 20))
        self.lineEdit_jump.setObjectName("lineEdit_jump")
        self.pushButton_jump = QtWidgets.QPushButton(Form)
        self.pushButton_jump.setGeometry(QtCore.QRect(620, 770, 41, 21))
        self.pushButton_jump.setObjectName("pushButton_jump")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(520, 760, 91, 39))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(20, 480, 51, 39))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(20, 420, 51, 39))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(30, 640, 51, 39))
        self.label_12.setObjectName("label_12")
        self.textBrowser_payRecord1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_payRecord1.setGeometry(QtCore.QRect(90, 460, 161, 71))
        self.textBrowser_payRecord1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_payRecord1.setLineWidth(0)
        self.textBrowser_payRecord1.setObjectName("textBrowser_payRecord1")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(20, 120, 51, 39))
        self.label_14.setObjectName("label_14")
        self.label_shipDate1 = QtWidgets.QLabel(Form)
        self.label_shipDate1.setGeometry(QtCore.QRect(90, 100, 151, 21))
        self.label_shipDate1.setObjectName("label_shipDate1")
        self.label_sales1 = QtWidgets.QLabel(Form)
        self.label_sales1.setGeometry(QtCore.QRect(90, 250, 151, 21))
        self.label_sales1.setObjectName("label_sales1")
        self.label_production1 = QtWidgets.QLabel(Form)
        self.label_production1.setGeometry(QtCore.QRect(90, 160, 161, 21))
        self.label_production1.setObjectName("label_production1")
        self.label_model1 = QtWidgets.QLabel(Form)
        self.label_model1.setGeometry(QtCore.QRect(90, 190, 151, 21))
        self.label_model1.setObjectName("label_model1")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(30, 210, 41, 39))
        self.label_15.setObjectName("label_15")
        self.label_macID1 = QtWidgets.QLabel(Form)
        self.label_macID1.setGeometry(QtCore.QRect(90, 220, 151, 21))
        self.label_macID1.setObjectName("label_macID1")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(40, 300, 31, 39))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(40, 270, 31, 39))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(40, 330, 31, 39))
        self.label_18.setObjectName("label_18")
        self.label_number1 = QtWidgets.QLabel(Form)
        self.label_number1.setGeometry(QtCore.QRect(90, 310, 121, 21))
        self.label_number1.setObjectName("label_number1")
        self.label_unitPrice1 = QtWidgets.QLabel(Form)
        self.label_unitPrice1.setGeometry(QtCore.QRect(90, 280, 151, 21))
        self.label_unitPrice1.setObjectName("label_unitPrice1")
        self.label_amount1 = QtWidgets.QLabel(Form)
        self.label_amount1.setGeometry(QtCore.QRect(90, 340, 141, 21))
        self.label_amount1.setObjectName("label_amount1")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(30, 360, 41, 39))
        self.label_19.setObjectName("label_19")
        self.label_paid1 = QtWidgets.QLabel(Form)
        self.label_paid1.setGeometry(QtCore.QRect(90, 370, 151, 21))
        self.label_paid1.setObjectName("label_paid1")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(30, 390, 41, 39))
        self.label_20.setObjectName("label_20")
        self.label_receivable1 = QtWidgets.QLabel(Form)
        self.label_receivable1.setGeometry(QtCore.QRect(90, 400, 161, 21))
        self.label_receivable1.setObjectName("label_receivable1")
        self.label_payRemind1 = QtWidgets.QLabel(Form)
        self.label_payRemind1.setGeometry(QtCore.QRect(90, 430, 151, 21))
        self.label_payRemind1.setObjectName("label_payRemind1")
        self.textBrowser_shipTo1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_shipTo1.setGeometry(QtCore.QRect(90, 540, 161, 71))
        self.textBrowser_shipTo1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_shipTo1.setLineWidth(0)
        self.textBrowser_shipTo1.setObjectName("textBrowser_shipTo1")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(20, 550, 51, 39))
        self.label_21.setObjectName("label_21")
        self.textBrowser_remark1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_remark1.setGeometry(QtCore.QRect(90, 620, 161, 71))
        self.textBrowser_remark1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_remark1.setLineWidth(0)
        self.textBrowser_remark1.setObjectName("textBrowser_remark1")
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(250, 90, 21, 611))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(Form)
        self.line_9.setGeometry(QtCore.QRect(10, 690, 251, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(Form)
        self.line_10.setGeometry(QtCore.QRect(0, 90, 20, 611))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(Form)
        self.line_11.setGeometry(QtCore.QRect(70, 90, 20, 611))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.pushButton_search = QtWidgets.QPushButton(Form)
        self.pushButton_search.setGeometry(QtCore.QRect(280, 10, 41, 21))
        self.pushButton_search.setObjectName("pushButton_search")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(10, 740, 1291, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_SwitchShipment = QtWidgets.QPushButton(Form)
        self.pushButton_SwitchShipment.setGeometry(QtCore.QRect(980, 10, 81, 23))
        self.pushButton_SwitchShipment.setObjectName("pushButton_SwitchShipment")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(360, 760, 141, 39))
        self.label_22.setObjectName("label_22")
        self.label_cPage = QtWidgets.QLabel(Form)
        self.label_cPage.setGeometry(QtCore.QRect(380, 770, 41, 21))
        self.label_cPage.setObjectName("label_cPage")
        self.label_tPage = QtWidgets.QLabel(Form)
        self.label_tPage.setGeometry(QtCore.QRect(430, 770, 41, 21))
        self.label_tPage.setObjectName("label_tPage")
        self.pushButton_edit2 = QtWidgets.QPushButton(Form)
        self.pushButton_edit2.setGeometry(QtCore.QRect(270, 710, 71, 23))
        self.pushButton_edit2.setObjectName("pushButton_edit2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(280, 240, 61, 39))
        self.label_6.setObjectName("label_6")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(280, 480, 51, 39))
        self.label_25.setObjectName("label_25")
        self.label_model2 = QtWidgets.QLabel(Form)
        self.label_model2.setGeometry(QtCore.QRect(350, 190, 161, 21))
        self.label_model2.setObjectName("label_model2")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(290, 390, 41, 39))
        self.label_26.setObjectName("label_26")
        self.line_12 = QtWidgets.QFrame(Form)
        self.line_12.setGeometry(QtCore.QRect(270, 690, 251, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.label_macID2 = QtWidgets.QLabel(Form)
        self.label_macID2.setGeometry(QtCore.QRect(350, 220, 151, 21))
        self.label_macID2.setObjectName("label_macID2")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(280, 150, 61, 39))
        self.label_7.setObjectName("label_7")
        self.label_production2 = QtWidgets.QLabel(Form)
        self.label_production2.setGeometry(QtCore.QRect(350, 160, 161, 21))
        self.label_production2.setObjectName("label_production2")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(280, 180, 61, 39))
        self.label_27.setObjectName("label_27")
        self.label_paid2 = QtWidgets.QLabel(Form)
        self.label_paid2.setGeometry(QtCore.QRect(350, 370, 151, 21))
        self.label_paid2.setObjectName("label_paid2")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(280, 420, 51, 39))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(290, 210, 41, 39))
        self.label_29.setObjectName("label_29")
        self.label_receivable2 = QtWidgets.QLabel(Form)
        self.label_receivable2.setGeometry(QtCore.QRect(350, 400, 151, 21))
        self.label_receivable2.setObjectName("label_receivable2")
        self.line_13 = QtWidgets.QFrame(Form)
        self.line_13.setGeometry(QtCore.QRect(510, 90, 21, 611))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(Form)
        self.line_14.setGeometry(QtCore.QRect(260, 90, 20, 611))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.textBrowser_payRecord2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_payRecord2.setGeometry(QtCore.QRect(350, 460, 161, 71))
        self.textBrowser_payRecord2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_payRecord2.setLineWidth(0)
        self.textBrowser_payRecord2.setObjectName("textBrowser_payRecord2")
        self.line_15 = QtWidgets.QFrame(Form)
        self.line_15.setGeometry(QtCore.QRect(270, 80, 251, 20))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(280, 550, 51, 39))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(290, 640, 51, 39))
        self.label_31.setObjectName("label_31")
        self.label_customer2 = QtWidgets.QLabel(Form)
        self.label_customer2.setGeometry(QtCore.QRect(350, 130, 161, 21))
        self.label_customer2.setObjectName("label_customer2")
        self.textBrowser_remark2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_remark2.setGeometry(QtCore.QRect(350, 620, 161, 71))
        self.textBrowser_remark2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_remark2.setLineWidth(0)
        self.textBrowser_remark2.setObjectName("textBrowser_remark2")
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setGeometry(QtCore.QRect(300, 270, 31, 39))
        self.label_32.setObjectName("label_32")
        self.line_16 = QtWidgets.QFrame(Form)
        self.line_16.setGeometry(QtCore.QRect(330, 90, 20, 611))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(300, 300, 31, 39))
        self.label_33.setObjectName("label_33")
        self.textBrowser_shipTo2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_shipTo2.setGeometry(QtCore.QRect(350, 540, 161, 71))
        self.textBrowser_shipTo2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_shipTo2.setLineWidth(0)
        self.textBrowser_shipTo2.setObjectName("textBrowser_shipTo2")
        self.label_34 = QtWidgets.QLabel(Form)
        self.label_34.setGeometry(QtCore.QRect(280, 120, 51, 39))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(Form)
        self.label_35.setGeometry(QtCore.QRect(280, 90, 61, 39))
        self.label_35.setObjectName("label_35")
        self.label_payRemind2 = QtWidgets.QLabel(Form)
        self.label_payRemind2.setGeometry(QtCore.QRect(350, 430, 151, 21))
        self.label_payRemind2.setObjectName("label_payRemind2")
        self.label_number2 = QtWidgets.QLabel(Form)
        self.label_number2.setGeometry(QtCore.QRect(350, 310, 141, 21))
        self.label_number2.setObjectName("label_number2")
        self.label_sales2 = QtWidgets.QLabel(Form)
        self.label_sales2.setGeometry(QtCore.QRect(350, 250, 151, 21))
        self.label_sales2.setObjectName("label_sales2")
        self.label_36 = QtWidgets.QLabel(Form)
        self.label_36.setGeometry(QtCore.QRect(300, 330, 31, 39))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(Form)
        self.label_37.setGeometry(QtCore.QRect(290, 360, 41, 39))
        self.label_37.setObjectName("label_37")
        self.label_unitPrice2 = QtWidgets.QLabel(Form)
        self.label_unitPrice2.setGeometry(QtCore.QRect(350, 280, 161, 21))
        self.label_unitPrice2.setObjectName("label_unitPrice2")
        self.label_shipDate2 = QtWidgets.QLabel(Form)
        self.label_shipDate2.setGeometry(QtCore.QRect(350, 100, 151, 21))
        self.label_shipDate2.setObjectName("label_shipDate2")
        self.label_amount2 = QtWidgets.QLabel(Form)
        self.label_amount2.setGeometry(QtCore.QRect(350, 340, 151, 21))
        self.label_amount2.setObjectName("label_amount2")
        self.pushButton_edit3 = QtWidgets.QPushButton(Form)
        self.pushButton_edit3.setGeometry(QtCore.QRect(530, 710, 71, 23))
        self.pushButton_edit3.setObjectName("pushButton_edit3")
        self.label_38 = QtWidgets.QLabel(Form)
        self.label_38.setGeometry(QtCore.QRect(540, 180, 61, 39))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(Form)
        self.label_39.setGeometry(QtCore.QRect(550, 390, 41, 39))
        self.label_39.setObjectName("label_39")
        self.textBrowser_payRecord3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_payRecord3.setGeometry(QtCore.QRect(610, 460, 161, 71))
        self.textBrowser_payRecord3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_payRecord3.setLineWidth(0)
        self.textBrowser_payRecord3.setObjectName("textBrowser_payRecord3")
        self.label_sales3 = QtWidgets.QLabel(Form)
        self.label_sales3.setGeometry(QtCore.QRect(610, 250, 161, 21))
        self.label_sales3.setObjectName("label_sales3")
        self.label_40 = QtWidgets.QLabel(Form)
        self.label_40.setGeometry(QtCore.QRect(550, 210, 41, 39))
        self.label_40.setObjectName("label_40")
        self.textBrowser_shipTo3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_shipTo3.setGeometry(QtCore.QRect(610, 540, 161, 71))
        self.textBrowser_shipTo3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_shipTo3.setLineWidth(0)
        self.textBrowser_shipTo3.setObjectName("textBrowser_shipTo3")
        self.label_41 = QtWidgets.QLabel(Form)
        self.label_41.setGeometry(QtCore.QRect(540, 240, 61, 39))
        self.label_41.setObjectName("label_41")
        self.line_17 = QtWidgets.QFrame(Form)
        self.line_17.setGeometry(QtCore.QRect(590, 90, 20, 611))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.label_42 = QtWidgets.QLabel(Form)
        self.label_42.setGeometry(QtCore.QRect(540, 550, 51, 39))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(Form)
        self.label_43.setGeometry(QtCore.QRect(550, 360, 41, 39))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(Form)
        self.label_44.setGeometry(QtCore.QRect(560, 330, 31, 39))
        self.label_44.setObjectName("label_44")
        self.label_model3 = QtWidgets.QLabel(Form)
        self.label_model3.setGeometry(QtCore.QRect(610, 190, 161, 21))
        self.label_model3.setObjectName("label_model3")
        self.label_45 = QtWidgets.QLabel(Form)
        self.label_45.setGeometry(QtCore.QRect(540, 150, 61, 39))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(Form)
        self.label_46.setGeometry(QtCore.QRect(550, 640, 51, 39))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(Form)
        self.label_47.setGeometry(QtCore.QRect(560, 270, 31, 39))
        self.label_47.setObjectName("label_47")
        self.line_18 = QtWidgets.QFrame(Form)
        self.line_18.setGeometry(QtCore.QRect(530, 80, 251, 20))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.label_shipDate3 = QtWidgets.QLabel(Form)
        self.label_shipDate3.setGeometry(QtCore.QRect(610, 100, 151, 21))
        self.label_shipDate3.setObjectName("label_shipDate3")
        self.label_48 = QtWidgets.QLabel(Form)
        self.label_48.setGeometry(QtCore.QRect(540, 120, 51, 39))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(Form)
        self.label_49.setGeometry(QtCore.QRect(560, 300, 31, 39))
        self.label_49.setObjectName("label_49")
        self.line_19 = QtWidgets.QFrame(Form)
        self.line_19.setGeometry(QtCore.QRect(770, 90, 21, 611))
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.label_unitPrice3 = QtWidgets.QLabel(Form)
        self.label_unitPrice3.setGeometry(QtCore.QRect(610, 280, 151, 21))
        self.label_unitPrice3.setObjectName("label_unitPrice3")
        self.label_amount3 = QtWidgets.QLabel(Form)
        self.label_amount3.setGeometry(QtCore.QRect(610, 340, 151, 21))
        self.label_amount3.setObjectName("label_amount3")
        self.line_20 = QtWidgets.QFrame(Form)
        self.line_20.setGeometry(QtCore.QRect(520, 90, 20, 611))
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.label_customer3 = QtWidgets.QLabel(Form)
        self.label_customer3.setGeometry(QtCore.QRect(610, 130, 161, 21))
        self.label_customer3.setObjectName("label_customer3")
        self.label_number3 = QtWidgets.QLabel(Form)
        self.label_number3.setGeometry(QtCore.QRect(610, 310, 131, 21))
        self.label_number3.setObjectName("label_number3")
        self.label_production3 = QtWidgets.QLabel(Form)
        self.label_production3.setGeometry(QtCore.QRect(610, 160, 161, 21))
        self.label_production3.setObjectName("label_production3")
        self.label_50 = QtWidgets.QLabel(Form)
        self.label_50.setGeometry(QtCore.QRect(540, 90, 61, 39))
        self.label_50.setObjectName("label_50")
        self.label_paid3 = QtWidgets.QLabel(Form)
        self.label_paid3.setGeometry(QtCore.QRect(610, 370, 151, 21))
        self.label_paid3.setObjectName("label_paid3")
        self.label_payRemind3 = QtWidgets.QLabel(Form)
        self.label_payRemind3.setGeometry(QtCore.QRect(610, 430, 151, 21))
        self.label_payRemind3.setObjectName("label_payRemind3")
        self.label_51 = QtWidgets.QLabel(Form)
        self.label_51.setGeometry(QtCore.QRect(540, 420, 51, 39))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(Form)
        self.label_52.setGeometry(QtCore.QRect(540, 480, 51, 39))
        self.label_52.setObjectName("label_52")
        self.line_21 = QtWidgets.QFrame(Form)
        self.line_21.setGeometry(QtCore.QRect(530, 690, 251, 20))
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.textBrowser_remark3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_remark3.setGeometry(QtCore.QRect(610, 620, 161, 71))
        self.textBrowser_remark3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_remark3.setLineWidth(0)
        self.textBrowser_remark3.setObjectName("textBrowser_remark3")
        self.label_macID3 = QtWidgets.QLabel(Form)
        self.label_macID3.setGeometry(QtCore.QRect(610, 220, 161, 21))
        self.label_macID3.setObjectName("label_macID3")
        self.label_receivable3 = QtWidgets.QLabel(Form)
        self.label_receivable3.setGeometry(QtCore.QRect(610, 400, 151, 21))
        self.label_receivable3.setObjectName("label_receivable3")
        self.pushButton_edit4 = QtWidgets.QPushButton(Form)
        self.pushButton_edit4.setGeometry(QtCore.QRect(790, 710, 71, 23))
        self.pushButton_edit4.setObjectName("pushButton_edit4")
        self.label_53 = QtWidgets.QLabel(Form)
        self.label_53.setGeometry(QtCore.QRect(800, 180, 61, 39))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(Form)
        self.label_54.setGeometry(QtCore.QRect(810, 390, 41, 39))
        self.label_54.setObjectName("label_54")
        self.textBrowser_payRecord4 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_payRecord4.setGeometry(QtCore.QRect(870, 460, 161, 71))
        self.textBrowser_payRecord4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_payRecord4.setLineWidth(0)
        self.textBrowser_payRecord4.setObjectName("textBrowser_payRecord4")
        self.label_sales4 = QtWidgets.QLabel(Form)
        self.label_sales4.setGeometry(QtCore.QRect(870, 250, 161, 21))
        self.label_sales4.setObjectName("label_sales4")
        self.label_55 = QtWidgets.QLabel(Form)
        self.label_55.setGeometry(QtCore.QRect(810, 210, 41, 39))
        self.label_55.setObjectName("label_55")
        self.textBrowser_shipTo4 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_shipTo4.setGeometry(QtCore.QRect(870, 540, 161, 71))
        self.textBrowser_shipTo4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_shipTo4.setLineWidth(0)
        self.textBrowser_shipTo4.setObjectName("textBrowser_shipTo4")
        self.label_56 = QtWidgets.QLabel(Form)
        self.label_56.setGeometry(QtCore.QRect(800, 240, 61, 39))
        self.label_56.setObjectName("label_56")
        self.line_22 = QtWidgets.QFrame(Form)
        self.line_22.setGeometry(QtCore.QRect(850, 90, 20, 611))
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.label_57 = QtWidgets.QLabel(Form)
        self.label_57.setGeometry(QtCore.QRect(800, 550, 51, 39))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(Form)
        self.label_58.setGeometry(QtCore.QRect(810, 360, 41, 39))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(Form)
        self.label_59.setGeometry(QtCore.QRect(820, 330, 31, 39))
        self.label_59.setObjectName("label_59")
        self.label_model4 = QtWidgets.QLabel(Form)
        self.label_model4.setGeometry(QtCore.QRect(870, 190, 161, 21))
        self.label_model4.setObjectName("label_model4")
        self.label_60 = QtWidgets.QLabel(Form)
        self.label_60.setGeometry(QtCore.QRect(800, 150, 61, 39))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(Form)
        self.label_61.setGeometry(QtCore.QRect(810, 640, 51, 39))
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(Form)
        self.label_62.setGeometry(QtCore.QRect(820, 270, 31, 39))
        self.label_62.setObjectName("label_62")
        self.line_23 = QtWidgets.QFrame(Form)
        self.line_23.setGeometry(QtCore.QRect(790, 80, 251, 20))
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.label_shipDate4 = QtWidgets.QLabel(Form)
        self.label_shipDate4.setGeometry(QtCore.QRect(870, 100, 161, 21))
        self.label_shipDate4.setObjectName("label_shipDate4")
        self.label_63 = QtWidgets.QLabel(Form)
        self.label_63.setGeometry(QtCore.QRect(800, 120, 51, 39))
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(Form)
        self.label_64.setGeometry(QtCore.QRect(820, 300, 31, 39))
        self.label_64.setObjectName("label_64")
        self.line_24 = QtWidgets.QFrame(Form)
        self.line_24.setGeometry(QtCore.QRect(1030, 90, 21, 611))
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.label_unitPrice4 = QtWidgets.QLabel(Form)
        self.label_unitPrice4.setGeometry(QtCore.QRect(870, 280, 161, 21))
        self.label_unitPrice4.setObjectName("label_unitPrice4")
        self.label_amount4 = QtWidgets.QLabel(Form)
        self.label_amount4.setGeometry(QtCore.QRect(870, 340, 151, 21))
        self.label_amount4.setObjectName("label_amount4")
        self.line_25 = QtWidgets.QFrame(Form)
        self.line_25.setGeometry(QtCore.QRect(780, 90, 20, 611))
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.label_customer4 = QtWidgets.QLabel(Form)
        self.label_customer4.setGeometry(QtCore.QRect(870, 130, 161, 21))
        self.label_customer4.setObjectName("label_customer4")
        self.label_number4 = QtWidgets.QLabel(Form)
        self.label_number4.setGeometry(QtCore.QRect(870, 310, 151, 21))
        self.label_number4.setObjectName("label_number4")
        self.label_production4 = QtWidgets.QLabel(Form)
        self.label_production4.setGeometry(QtCore.QRect(870, 160, 161, 21))
        self.label_production4.setObjectName("label_production4")
        self.label_65 = QtWidgets.QLabel(Form)
        self.label_65.setGeometry(QtCore.QRect(800, 90, 61, 39))
        self.label_65.setObjectName("label_65")
        self.label_paid4 = QtWidgets.QLabel(Form)
        self.label_paid4.setGeometry(QtCore.QRect(870, 370, 161, 21))
        self.label_paid4.setObjectName("label_paid4")
        self.label_payRemind4 = QtWidgets.QLabel(Form)
        self.label_payRemind4.setGeometry(QtCore.QRect(870, 430, 151, 21))
        self.label_payRemind4.setObjectName("label_payRemind4")
        self.label_66 = QtWidgets.QLabel(Form)
        self.label_66.setGeometry(QtCore.QRect(800, 420, 51, 39))
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(Form)
        self.label_67.setGeometry(QtCore.QRect(800, 480, 51, 39))
        self.label_67.setObjectName("label_67")
        self.line_26 = QtWidgets.QFrame(Form)
        self.line_26.setGeometry(QtCore.QRect(790, 690, 251, 20))
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.textBrowser_remark4 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_remark4.setGeometry(QtCore.QRect(870, 620, 161, 71))
        self.textBrowser_remark4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_remark4.setLineWidth(0)
        self.textBrowser_remark4.setObjectName("textBrowser_remark4")
        self.label_macID4 = QtWidgets.QLabel(Form)
        self.label_macID4.setGeometry(QtCore.QRect(870, 220, 161, 21))
        self.label_macID4.setObjectName("label_macID4")
        self.label_receivable4 = QtWidgets.QLabel(Form)
        self.label_receivable4.setGeometry(QtCore.QRect(870, 400, 151, 21))
        self.label_receivable4.setObjectName("label_receivable4")
        self.pushButton_edit5 = QtWidgets.QPushButton(Form)
        self.pushButton_edit5.setGeometry(QtCore.QRect(1050, 710, 71, 23))
        self.pushButton_edit5.setObjectName("pushButton_edit5")
        self.label_68 = QtWidgets.QLabel(Form)
        self.label_68.setGeometry(QtCore.QRect(1060, 180, 61, 39))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(Form)
        self.label_69.setGeometry(QtCore.QRect(1070, 390, 41, 39))
        self.label_69.setObjectName("label_69")
        self.textBrowser_payRecord5 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_payRecord5.setGeometry(QtCore.QRect(1130, 460, 161, 71))
        self.textBrowser_payRecord5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_payRecord5.setLineWidth(0)
        self.textBrowser_payRecord5.setObjectName("textBrowser_payRecord5")
        self.label_sales5 = QtWidgets.QLabel(Form)
        self.label_sales5.setGeometry(QtCore.QRect(1130, 250, 161, 21))
        self.label_sales5.setObjectName("label_sales5")
        self.label_70 = QtWidgets.QLabel(Form)
        self.label_70.setGeometry(QtCore.QRect(1070, 210, 41, 39))
        self.label_70.setObjectName("label_70")
        self.textBrowser_shipTo5 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_shipTo5.setGeometry(QtCore.QRect(1130, 540, 161, 71))
        self.textBrowser_shipTo5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_shipTo5.setLineWidth(0)
        self.textBrowser_shipTo5.setObjectName("textBrowser_shipTo5")
        self.label_71 = QtWidgets.QLabel(Form)
        self.label_71.setGeometry(QtCore.QRect(1060, 240, 61, 39))
        self.label_71.setObjectName("label_71")
        self.line_27 = QtWidgets.QFrame(Form)
        self.line_27.setGeometry(QtCore.QRect(1110, 90, 20, 611))
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.label_72 = QtWidgets.QLabel(Form)
        self.label_72.setGeometry(QtCore.QRect(1060, 550, 51, 39))
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(Form)
        self.label_73.setGeometry(QtCore.QRect(1070, 360, 41, 39))
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(Form)
        self.label_74.setGeometry(QtCore.QRect(1080, 330, 31, 39))
        self.label_74.setObjectName("label_74")
        self.label_model5 = QtWidgets.QLabel(Form)
        self.label_model5.setGeometry(QtCore.QRect(1130, 190, 151, 21))
        self.label_model5.setObjectName("label_model5")
        self.label_75 = QtWidgets.QLabel(Form)
        self.label_75.setGeometry(QtCore.QRect(1060, 150, 61, 39))
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(Form)
        self.label_76.setGeometry(QtCore.QRect(1070, 640, 51, 39))
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(Form)
        self.label_77.setGeometry(QtCore.QRect(1080, 270, 31, 39))
        self.label_77.setObjectName("label_77")
        self.line_28 = QtWidgets.QFrame(Form)
        self.line_28.setGeometry(QtCore.QRect(1050, 80, 251, 20))
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.label_shipDate5 = QtWidgets.QLabel(Form)
        self.label_shipDate5.setGeometry(QtCore.QRect(1130, 100, 151, 21))
        self.label_shipDate5.setObjectName("label_shipDate5")
        self.label_78 = QtWidgets.QLabel(Form)
        self.label_78.setGeometry(QtCore.QRect(1060, 120, 51, 39))
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(Form)
        self.label_79.setGeometry(QtCore.QRect(1080, 300, 31, 39))
        self.label_79.setObjectName("label_79")
        self.line_29 = QtWidgets.QFrame(Form)
        self.line_29.setGeometry(QtCore.QRect(1290, 90, 21, 611))
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.label_unitPrice5 = QtWidgets.QLabel(Form)
        self.label_unitPrice5.setGeometry(QtCore.QRect(1130, 280, 161, 21))
        self.label_unitPrice5.setObjectName("label_unitPrice5")
        self.label_amount5 = QtWidgets.QLabel(Form)
        self.label_amount5.setGeometry(QtCore.QRect(1130, 340, 161, 21))
        self.label_amount5.setObjectName("label_amount5")
        self.line_30 = QtWidgets.QFrame(Form)
        self.line_30.setGeometry(QtCore.QRect(1040, 90, 20, 611))
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.label_customer5 = QtWidgets.QLabel(Form)
        self.label_customer5.setGeometry(QtCore.QRect(1130, 130, 161, 21))
        self.label_customer5.setObjectName("label_customer5")
        self.label_number5 = QtWidgets.QLabel(Form)
        self.label_number5.setGeometry(QtCore.QRect(1130, 310, 151, 21))
        self.label_number5.setObjectName("label_number5")
        self.label_production5 = QtWidgets.QLabel(Form)
        self.label_production5.setGeometry(QtCore.QRect(1130, 160, 161, 21))
        self.label_production5.setObjectName("label_production5")
        self.label_80 = QtWidgets.QLabel(Form)
        self.label_80.setGeometry(QtCore.QRect(1060, 90, 61, 39))
        self.label_80.setObjectName("label_80")
        self.label_paid5 = QtWidgets.QLabel(Form)
        self.label_paid5.setGeometry(QtCore.QRect(1130, 370, 161, 21))
        self.label_paid5.setObjectName("label_paid5")
        self.label_payRemind5 = QtWidgets.QLabel(Form)
        self.label_payRemind5.setGeometry(QtCore.QRect(1130, 430, 161, 21))
        self.label_payRemind5.setObjectName("label_payRemind5")
        self.label_81 = QtWidgets.QLabel(Form)
        self.label_81.setGeometry(QtCore.QRect(1060, 420, 51, 39))
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(Form)
        self.label_82.setGeometry(QtCore.QRect(1060, 480, 51, 39))
        self.label_82.setObjectName("label_82")
        self.line_31 = QtWidgets.QFrame(Form)
        self.line_31.setGeometry(QtCore.QRect(1050, 690, 251, 20))
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.textBrowser_remark5 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_remark5.setGeometry(QtCore.QRect(1130, 620, 161, 71))
        self.textBrowser_remark5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_remark5.setLineWidth(0)
        self.textBrowser_remark5.setObjectName("textBrowser_remark5")
        self.label_macID5 = QtWidgets.QLabel(Form)
        self.label_macID5.setGeometry(QtCore.QRect(1130, 220, 161, 21))
        self.label_macID5.setObjectName("label_macID5")
        self.label_receivable5 = QtWidgets.QLabel(Form)
        self.label_receivable5.setGeometry(QtCore.QRect(1130, 400, 151, 21))
        self.label_receivable5.setObjectName("label_receivable5")
        self.label_order1 = QtWidgets.QLabel(Form)
        self.label_order1.setGeometry(QtCore.QRect(150, 710, 41, 21))
        self.label_order1.setObjectName("label_order1")
        self.label_id2 = QtWidgets.QLabel(Form)
        self.label_id2.setGeometry(QtCore.QRect(390, 60, 91, 21))
        self.label_id2.setObjectName("label_id2")
        self.label_order2 = QtWidgets.QLabel(Form)
        self.label_order2.setGeometry(QtCore.QRect(410, 710, 41, 21))
        self.label_order2.setObjectName("label_order2")
        self.label_id3 = QtWidgets.QLabel(Form)
        self.label_id3.setGeometry(QtCore.QRect(650, 60, 91, 21))
        self.label_id3.setObjectName("label_id3")
        self.label_order3 = QtWidgets.QLabel(Form)
        self.label_order3.setGeometry(QtCore.QRect(660, 710, 41, 21))
        self.label_order3.setObjectName("label_order3")
        self.label_id4 = QtWidgets.QLabel(Form)
        self.label_id4.setGeometry(QtCore.QRect(910, 60, 91, 21))
        self.label_id4.setObjectName("label_id4")
        self.label_order4 = QtWidgets.QLabel(Form)
        self.label_order4.setGeometry(QtCore.QRect(930, 710, 41, 21))
        self.label_order4.setObjectName("label_order4")
        self.label_id5 = QtWidgets.QLabel(Form)
        self.label_id5.setGeometry(QtCore.QRect(1170, 60, 91, 21))
        self.label_id5.setObjectName("label_id5")
        self.label_order5 = QtWidgets.QLabel(Form)
        self.label_order5.setGeometry(QtCore.QRect(1190, 710, 41, 21))
        self.label_order5.setObjectName("label_order5")
        self.label_13.raise_()
        self.label_id1.raise_()
        self.lineEdit_search.raise_()
        self.label_customer1.raise_()
        self.line_7.raise_()
        self.pushButton_SwitchCustomer.raise_()
        self.pushButton_edit1.raise_()
        self.label_4.raise_()
        self.line.raise_()
        self.pushButton_SwitchService.raise_()
        self.label_8.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton_previous.raise_()
        self.pushButton_next.raise_()
        self.pushButton_new.raise_()
        self.pushButton_jump.raise_()
        self.label_9.raise_()
        self.lineEdit_jump.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.textBrowser_payRecord1.raise_()
        self.label_14.raise_()
        self.label_shipDate1.raise_()
        self.label_sales1.raise_()
        self.label_production1.raise_()
        self.label_model1.raise_()
        self.label_15.raise_()
        self.label_macID1.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_number1.raise_()
        self.label_unitPrice1.raise_()
        self.label_amount1.raise_()
        self.label_19.raise_()
        self.label_paid1.raise_()
        self.label_20.raise_()
        self.label_receivable1.raise_()
        self.label_payRemind1.raise_()
        self.textBrowser_shipTo1.raise_()
        self.label_21.raise_()
        self.textBrowser_remark1.raise_()
        self.line_8.raise_()
        self.line_9.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        self.pushButton_search.raise_()
        self.line_2.raise_()
        self.pushButton_SwitchShipment.raise_()
        self.label_22.raise_()
        self.label_cPage.raise_()
        self.label_tPage.raise_()
        self.pushButton_edit2.raise_()
        self.label_6.raise_()
        self.label_25.raise_()
        self.label_model2.raise_()
        self.label_26.raise_()
        self.line_12.raise_()
        self.label_macID2.raise_()
        self.label_7.raise_()
        self.label_production2.raise_()
        self.label_27.raise_()
        self.label_paid2.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_receivable2.raise_()
        self.line_13.raise_()
        self.line_14.raise_()
        self.textBrowser_payRecord2.raise_()
        self.line_15.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.label_customer2.raise_()
        self.textBrowser_remark2.raise_()
        self.label_32.raise_()
        self.line_16.raise_()
        self.label_33.raise_()
        self.textBrowser_shipTo2.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_payRemind2.raise_()
        self.label_number2.raise_()
        self.label_sales2.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_unitPrice2.raise_()
        self.label_shipDate2.raise_()
        self.label_amount2.raise_()
        self.pushButton_edit3.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.textBrowser_payRecord3.raise_()
        self.label_sales3.raise_()
        self.label_40.raise_()
        self.textBrowser_shipTo3.raise_()
        self.label_41.raise_()
        self.line_17.raise_()
        self.label_42.raise_()
        self.label_43.raise_()
        self.label_44.raise_()
        self.label_model3.raise_()
        self.label_45.raise_()
        self.label_46.raise_()
        self.label_47.raise_()
        self.line_18.raise_()
        self.label_shipDate3.raise_()
        self.label_48.raise_()
        self.label_49.raise_()
        self.line_19.raise_()
        self.label_unitPrice3.raise_()
        self.label_amount3.raise_()
        self.line_20.raise_()
        self.label_customer3.raise_()
        self.label_number3.raise_()
        self.label_production3.raise_()
        self.label_50.raise_()
        self.label_paid3.raise_()
        self.label_payRemind3.raise_()
        self.label_51.raise_()
        self.label_52.raise_()
        self.line_21.raise_()
        self.textBrowser_remark3.raise_()
        self.label_macID3.raise_()
        self.label_receivable3.raise_()
        self.pushButton_edit4.raise_()
        self.label_53.raise_()
        self.label_54.raise_()
        self.textBrowser_payRecord4.raise_()
        self.label_sales4.raise_()
        self.label_55.raise_()
        self.textBrowser_shipTo4.raise_()
        self.label_56.raise_()
        self.line_22.raise_()
        self.label_57.raise_()
        self.label_58.raise_()
        self.label_59.raise_()
        self.label_model4.raise_()
        self.label_60.raise_()
        self.label_61.raise_()
        self.label_62.raise_()
        self.line_23.raise_()
        self.label_shipDate4.raise_()
        self.label_63.raise_()
        self.label_64.raise_()
        self.line_24.raise_()
        self.label_unitPrice4.raise_()
        self.label_amount4.raise_()
        self.line_25.raise_()
        self.label_customer4.raise_()
        self.label_number4.raise_()
        self.label_production4.raise_()
        self.label_65.raise_()
        self.label_paid4.raise_()
        self.label_payRemind4.raise_()
        self.label_66.raise_()
        self.label_67.raise_()
        self.line_26.raise_()
        self.textBrowser_remark4.raise_()
        self.label_macID4.raise_()
        self.label_receivable4.raise_()
        self.pushButton_edit5.raise_()
        self.label_68.raise_()
        self.label_69.raise_()
        self.textBrowser_payRecord5.raise_()
        self.label_sales5.raise_()
        self.label_70.raise_()
        self.textBrowser_shipTo5.raise_()
        self.label_71.raise_()
        self.line_27.raise_()
        self.label_72.raise_()
        self.label_73.raise_()
        self.label_74.raise_()
        self.label_model5.raise_()
        self.label_75.raise_()
        self.label_76.raise_()
        self.label_77.raise_()
        self.line_28.raise_()
        self.label_shipDate5.raise_()
        self.label_78.raise_()
        self.label_79.raise_()
        self.line_29.raise_()
        self.label_unitPrice5.raise_()
        self.label_amount5.raise_()
        self.line_30.raise_()
        self.label_customer5.raise_()
        self.label_number5.raise_()
        self.label_production5.raise_()
        self.label_80.raise_()
        self.label_paid5.raise_()
        self.label_payRemind5.raise_()
        self.label_81.raise_()
        self.label_82.raise_()
        self.line_31.raise_()
        self.textBrowser_remark5.raise_()
        self.label_macID5.raise_()
        self.label_receivable5.raise_()
        self.label_order1.raise_()
        self.label_id2.raise_()
        self.label_order2.raise_()
        self.label_id3.raise_()
        self.label_order3.raise_()
        self.label_id4.raise_()
        self.label_order4.raise_()
        self.label_id5.raise_()
        self.label_order5.raise_()

        self.retranslateUi(Form)
        self.pushButton_previous.clicked.connect(self.reloadWidgetDec)
        self.pushButton_next.clicked.connect(self.reloadWidgetAdd)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#0b3da8;\">产品出货记录</span></p></body></html>"))
        self.label_id1.setText(_translate("Form", "shipmentID"))
        self.label_customer1.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#063661;\">customer</span></p></body></html>"))
        self.pushButton_SwitchCustomer.setText(_translate("Form", "客户信息界面"))
        self.pushButton_edit1.setText(_translate("Form", "编辑"))
        self.label_4.setText(_translate("Form", "出货产品"))
        self.pushButton_SwitchService.setText(_translate("Form", "售后服务记录"))
        self.label_8.setText(_translate("Form", "搜索"))
        self.label_5.setText(_translate("Form", "规格型号"))
        self.label_2.setText(_translate("Form", "出货日期"))
        self.label_3.setText(_translate("Form", "业务负责"))
        self.pushButton_previous.setText(_translate("Form", "上一页"))
        self.pushButton_next.setText(_translate("Form", "下一页"))
        self.pushButton_new.setText(_translate("Form", "新增出货信息"))
        self.pushButton_jump.setText(_translate("Form", "GO!"))
        self.label_9.setText(_translate("Form", "跳到第       页"))
        self.label_10.setText(_translate("Form", "付款记录"))
        self.label_11.setText(_translate("Form", "下次付款"))
        self.label_12.setText(_translate("Form", "备注"))
        self.textBrowser_payRecord1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">payRecord</p></body></html>"))
        self.label_14.setText(_translate("Form", "客户名称"))
        self.label_shipDate1.setText(_translate("Form", "shipDate"))
        self.label_sales1.setText(_translate("Form", "sales"))
        self.label_production1.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#063661;\">production</span></p></body></html>"))
        self.label_model1.setText(_translate("Form", "model"))
        self.label_15.setText(_translate("Form", "设备号"))
        self.label_macID1.setText(_translate("Form", "macID"))
        self.label_16.setText(_translate("Form", "数量"))
        self.label_17.setText(_translate("Form", "单价"))
        self.label_18.setText(_translate("Form", "金额"))
        self.label_number1.setText(_translate("Form", "number"))
        self.label_unitPrice1.setText(_translate("Form", "unitPrice"))
        self.label_amount1.setText(_translate("Form", "amount"))
        self.label_19.setText(_translate("Form", "已付款"))
        self.label_paid1.setText(_translate("Form", "paid"))
        self.label_20.setText(_translate("Form", "应收款"))
        self.label_receivable1.setText(_translate("Form", "receivable"))
        self.label_payRemind1.setText(_translate("Form", "payRemind"))
        self.textBrowser_shipTo1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">shipto</p></body></html>"))
        self.label_21.setText(_translate("Form", "发货地址"))
        self.textBrowser_remark1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">remark</p></body></html>"))
        self.pushButton_search.setText(_translate("Form", "GO!"))
        self.pushButton_SwitchShipment.setText(_translate("Form", "产品出货信息"))
        self.label_22.setText(_translate("Form", "第        /         页"))
        self.label_cPage.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#063661;\">cPage</span></p></body></html>"))
        self.label_tPage.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#063661;\">tPage</span></p></body></html>"))
        self.pushButton_edit2.setText(_translate("Form", "编辑"))
        self.label_6.setText(_translate("Form", "业务负责"))
        self.label_25.setText(_translate("Form", "付款记录"))
        self.label_model2.setText(_translate("Form", "model"))
        self.label_26.setText(_translate("Form", "应收款"))
        self.label_macID2.setText(_translate("Form", "macID"))
        self.label_7.setText(_translate("Form", "出货产品"))
        self.label_production2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#063661;\">production</span></p></body></html>"))
        self.label_27.setText(_translate("Form", "规格型号"))
        self.label_paid2.setText(_translate("Form", "paid"))
        self.label_28.setText(_translate("Form", "下次付款"))
        self.label_29.setText(_translate("Form", "设备号"))
        self.label_receivable2.setText(_translate("Form", "receivable"))
        self.textBrowser_payRecord2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">payRecord</p></body></html>"))
        self.label_30.setText(_translate("Form", "发货地址"))
        self.label_31.setText(_translate("Form", "备注"))
        self.label_customer2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#063661;\">customer</span></p></body></html>"))
        self.textBrowser_remark2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">remark</p></body></html>"))
        self.label_32.setText(_translate("Form", "单价"))
        self.label_33.setText(_translate("Form", "数量"))
        self.textBrowser_shipTo2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">shipto</p></body></html>"))
        self.label_34.setText(_translate("Form", "客户名称"))
        self.label_35.setText(_translate("Form", "出货日期"))
        self.label_payRemind2.setText(_translate("Form", "payRemind"))
        self.label_number2.setText(_translate("Form", "number"))
        self.label_sales2.setText(_translate("Form", "sales"))
        self.label_36.setText(_translate("Form", "金额"))
        self.label_37.setText(_translate("Form", "已付款"))
        self.label_unitPrice2.setText(_translate("Form", "unitPrice"))
        self.label_shipDate2.setText(_translate("Form", "shipDate"))
        self.label_amount2.setText(_translate("Form", "amount"))
        self.pushButton_edit3.setText(_translate("Form", "编辑"))
        self.label_38.setText(_translate("Form", "规格型号"))
        self.label_39.setText(_translate("Form", "应收款"))
        self.textBrowser_payRecord3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">payRecord</p></body></html>"))
        self.label_sales3.setText(_translate("Form", "sales"))
        self.label_40.setText(_translate("Form", "设备号"))
        self.textBrowser_shipTo3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">shipto</p></body></html>"))
        self.label_41.setText(_translate("Form", "业务负责"))
        self.label_42.setText(_translate("Form", "发货地址"))
        self.label_43.setText(_translate("Form", "已付款"))
        self.label_44.setText(_translate("Form", "金额"))
        self.label_model3.setText(_translate("Form", "model"))
        self.label_45.setText(_translate("Form", "出货产品"))
        self.label_46.setText(_translate("Form", "备注"))
        self.label_47.setText(_translate("Form", "单价"))
        self.label_shipDate3.setText(_translate("Form", "shipDate"))
        self.label_48.setText(_translate("Form", "客户名称"))
        self.label_49.setText(_translate("Form", "数量"))
        self.label_unitPrice3.setText(_translate("Form", "unitPrice"))
        self.label_amount3.setText(_translate("Form", "amount"))
        self.label_customer3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#063661;\">customer</span></p></body></html>"))
        self.label_number3.setText(_translate("Form", "number"))
        self.label_production3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#063661;\">production</span></p></body></html>"))
        self.label_50.setText(_translate("Form", "出货日期"))
        self.label_paid3.setText(_translate("Form", "paid"))
        self.label_payRemind3.setText(_translate("Form", "payRemind"))
        self.label_51.setText(_translate("Form", "下次付款"))
        self.label_52.setText(_translate("Form", "付款记录"))
        self.textBrowser_remark3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">remark</p></body></html>"))
        self.label_macID3.setText(_translate("Form", "macID"))
        self.label_receivable3.setText(_translate("Form", "receivable"))
        self.pushButton_edit4.setText(_translate("Form", "编辑"))
        self.label_53.setText(_translate("Form", "规格型号"))
        self.label_54.setText(_translate("Form", "应收款"))
        self.textBrowser_payRecord4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">payRecord</p></body></html>"))
        self.label_sales4.setText(_translate("Form", "sales"))
        self.label_55.setText(_translate("Form", "设备号"))
        self.textBrowser_shipTo4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">shipto</p></body></html>"))
        self.label_56.setText(_translate("Form", "业务负责"))
        self.label_57.setText(_translate("Form", "发货地址"))
        self.label_58.setText(_translate("Form", "已付款"))
        self.label_59.setText(_translate("Form", "金额"))
        self.label_model4.setText(_translate("Form", "model"))
        self.label_60.setText(_translate("Form", "出货产品"))
        self.label_61.setText(_translate("Form", "备注"))
        self.label_62.setText(_translate("Form", "单价"))
        self.label_shipDate4.setText(_translate("Form", "shipDate"))
        self.label_63.setText(_translate("Form", "客户名称"))
        self.label_64.setText(_translate("Form", "数量"))
        self.label_unitPrice4.setText(_translate("Form", "unitPrice"))
        self.label_amount4.setText(_translate("Form", "amount"))
        self.label_customer4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#063661;\">customer</span></p></body></html>"))
        self.label_number4.setText(_translate("Form", "number"))
        self.label_production4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#063661;\">production</span></p></body></html>"))
        self.label_65.setText(_translate("Form", "出货日期"))
        self.label_paid4.setText(_translate("Form", "paid"))
        self.label_payRemind4.setText(_translate("Form", "payRemind"))
        self.label_66.setText(_translate("Form", "下次付款"))
        self.label_67.setText(_translate("Form", "付款记录"))
        self.textBrowser_remark4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">remark</p></body></html>"))
        self.label_macID4.setText(_translate("Form", "macID"))
        self.label_receivable4.setText(_translate("Form", "receivable"))
        self.pushButton_edit5.setText(_translate("Form", "编辑"))
        self.label_68.setText(_translate("Form", "规格型号"))
        self.label_69.setText(_translate("Form", "应收款"))
        self.textBrowser_payRecord5.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">payRecord</p></body></html>"))
        self.label_sales5.setText(_translate("Form", "sales"))
        self.label_70.setText(_translate("Form", "设备号"))
        self.textBrowser_shipTo5.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">shipto</p></body></html>"))
        self.label_71.setText(_translate("Form", "业务负责"))
        self.label_72.setText(_translate("Form", "发货地址"))
        self.label_73.setText(_translate("Form", "已付款"))
        self.label_74.setText(_translate("Form", "金额"))
        self.label_model5.setText(_translate("Form", "model"))
        self.label_75.setText(_translate("Form", "出货产品"))
        self.label_76.setText(_translate("Form", "备注"))
        self.label_77.setText(_translate("Form", "单价"))
        self.label_shipDate5.setText(_translate("Form", "shipDate"))
        self.label_78.setText(_translate("Form", "客户名称"))
        self.label_79.setText(_translate("Form", "数量"))
        self.label_unitPrice5.setText(_translate("Form", "unitPrice"))
        self.label_amount5.setText(_translate("Form", "amount"))
        self.label_customer5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#063661;\">customer</span></p></body></html>"))
        self.label_number5.setText(_translate("Form", "number"))
        self.label_production5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#063661;\">production</span></p></body></html>"))
        self.label_80.setText(_translate("Form", "出货日期"))
        self.label_paid5.setText(_translate("Form", "paid"))
        self.label_payRemind5.setText(_translate("Form", "payRemind"))
        self.label_81.setText(_translate("Form", "下次付款"))
        self.label_82.setText(_translate("Form", "付款记录"))
        self.textBrowser_remark5.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">remark</p></body></html>"))
        self.label_macID5.setText(_translate("Form", "macID"))
        self.label_receivable5.setText(_translate("Form", "receivable"))
        self.label_order1.setText(_translate("Form", "order"))
        self.label_id2.setText(_translate("Form", "shipmentID"))
        self.label_order2.setText(_translate("Form", "order"))
        self.label_id3.setText(_translate("Form", "shipmentID"))
        self.label_order3.setText(_translate("Form", "order"))
        self.label_id4.setText(_translate("Form", "shipmentID"))
        self.label_order4.setText(_translate("Form", "order"))
        self.label_id5.setText(_translate("Form", "shipmentID"))
        self.label_order5.setText(_translate("Form", "order"))

####以上为QTDesiger自动生成代码
###以下为自己写的代码
    def closeEvent(self, event):        #关闭窗口触发以下事件
        reply = QMessageBox.question(self, '消息提示', '你确定要退出吗?', QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
        if reply == QMessageBox.Yes:
            event.accept()        #接受关闭事件
        else:
            event.ignore()        #忽略关闭事件
    def reloadWidgetAdd(self,i): #点击下一页触发
        print ("reloadWidgeAdd")
        i= int(self.label_order5.text())
        dblen=self.dblen()
        if i < dblen: #dblen():
#            global g
            NextOffice.shipment.shipment_main.g=NextOffice.shipment.shipment_main.g+1 #全局变量P页数+1
            self.pageDisplay(NextOffice.shipment.shipment_main.g)
            print("shipment_main的g是",NextOffice.shipment.shipment_main.g)

        else:
            print("remain")
    def reloadWidgetDec(self,i): #点击上一页触发
        print ("reloadWidgeDec")
        i= int(self.label_order5.text())
        if i > 5:
            global g
            NextOffice.shipment.shipment_main.g=NextOffice.shipment.shipment_main.g-1 #全局变量P页数+1
#            g=g-1 #全局变量P页数-1
            self.pageDisplay(NextOffice.shipment.shipment_main.g)
        else:
            print("remain")
    def pageDisplay(self,g):  #本函数显示g页的数据
        print("shipment_browser: pageDisplay",g)
        orderE=g*5
        orderD=orderE-1
        orderC=orderE-2
        orderB=orderE-3
        orderA=orderE-4
        self.label_order1.setText(str(orderA))
        self.label_order2.setText(str(orderB))
        self.label_order3.setText(str(orderC))
        self.label_order4.setText(str(orderD))
        self.label_order5.setText(str(orderE))

        conn = sqlite3.connect('nextai.db')

        curs = conn.cursor()  #创建游标
#        print ("pageData()打开数据库成功")
        curs.execute("SELECT * from shipment")
        data= curs.fetchall() #data[]数组获得数据库中的全部数据
        curs.close()  #关闭游标
        conn.commit() #保存数据库
        conn.close() #关闭数据库连接

        p=g*5-4  #获得当前页面的第1行

        blank=["","","","","","","","0","0","0","","","","","",""]

        dblen=self.dblen()
        print("shipment_browser-pageDisplay:现在数据库中共有记录：",dblen)
        a=dblen%5 #计算最后一页总共有几行？
        b=5-a  #计算空白的有几行
#        c=0
        while b>0:#将当前页面的空白记录行填充N/A，以免data赋值的时候不够5行导致出错
            data.append(blank)
            if g == dblen//5+1:  #如果当前页面是最后一页---总页数/5然后+1
                if b==1: #如果只有1行空白
                    self.pushButton_edit5.hide() #隐藏最后一个编辑按钮
                elif b==2:#如果有2行空白
                    self.pushButton_edit4.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit5.hide()
                elif b==3:#如果有3行空白
                    self.pushButton_edit3.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit4.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit5.hide()
                elif b==4:#如果有4行空白
                    self.pushButton_edit2.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit3.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit4.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit5.hide()
            b=b-1

##计算出货产品价格与应收款
        unitPrice1=int(data[p-1][7])
        number1=int(data[p-1][8])
        amount1=unitPrice1*number1
        paid1=int(data[p-1][9])
        receivable1=amount1-paid1

        unitPrice2=int(data[p][7])
        number2=int(data[p][8])
        amount2=unitPrice2*number2
        paid2=int(data[p][9])
        receivable2=amount2-paid2

        unitPrice3=int(data[p+1][7])
        number3=int(data[p+1][8])
        amount3=unitPrice3*number3
        paid3=int(data[p+1][9])
        receivable3=amount3-paid3

        unitPrice4=int(data[p+2][7])
        number4=int(data[p+2][8])
        amount4=unitPrice4*number4
        paid4=int(data[p+2][9])
        receivable4=amount4-paid4

        unitPrice5=int(data[p+3][7])
        number5=int(data[p+3][8])
        amount5=unitPrice5*number5
        paid5=int(data[p+3][9])
        receivable5=amount5-paid5



#以下将数据库中获取的内容分别对应显示在5行内
        self.label_id1.setText(str(data[p-1][0])) #数据库是从0开始的，所以减1
        self.label_shipDate1.setText(str(data[p-1][1]))
        self.label_customer1.setText(str(data[p-1][2]))
        self.label_sales1.setText(str(data[p-1][3]))
        self.label_production1.setText(str(data[p-1][4]))
        self.label_model1.setText(str(data[p-1][5]))
        self.label_macID1.setText(str(data[p-1][6]))
        self.label_unitPrice1.setText(str(data[p-1][7]))
        self.label_number1.setText(str(data[p-1][8]))
        self.label_paid1.setText(str(data[p-1][9]))
        self.textBrowser_payRecord1.setText(str(data[p-1][10]))
        self.label_payRemind1.setText(str(data[p-1][11]))
        self.textBrowser_shipTo1.setText(str(data[p-1][12]))
        self.textBrowser_remark1.setText(str(data[p-1][13]))
        self.label_amount1.setText(str(amount1))
        self.label_receivable1.setText(str(receivable1))

        self.label_id2.setText(str(data[p][0])) #数据库是从0开始的，所以减1
        self.label_shipDate2.setText(str(data[p][1]))
        self.label_customer2.setText(str(data[p][2]))
        self.label_sales2.setText(str(data[p][3]))
        self.label_production2.setText(str(data[p][4]))
        self.label_model2.setText(str(data[p][5]))
        self.label_macID2.setText(str(data[p][6]))
        self.label_unitPrice2.setText(str(data[p][7]))
        self.label_number2.setText(str(data[p][8]))
#        self.label_amount2.setText(str(data[p][9]))
        self.label_paid2.setText(str(data[p][9]))
#        self.label_receivable2.setText(str(data[p][11]))
        self.textBrowser_payRecord2.setText(str(data[p][10]))
        self.label_payRemind2.setText(str(data[p][11]))
        self.textBrowser_shipTo2.setText(str(data[p][12]))
        self.textBrowser_remark2.setText(str(data[p][13]))
        self.label_amount2.setText(str(amount2))
        self.label_receivable2.setText(str(receivable2))

        self.label_id3.setText(str(data[p+1][0])) #数据库是从0开始的，所以减1
        self.label_shipDate3.setText(str(data[p+1][1]))
        self.label_customer3.setText(str(data[p+1][2]))
        self.label_sales3.setText(str(data[p+1][3]))
        self.label_production3.setText(str(data[p+1][4]))
        self.label_model3.setText(str(data[p+1][5]))
        self.label_macID3.setText(str(data[p+1][6]))
        self.label_unitPrice3.setText(str(data[p+1][7]))
        self.label_number3.setText(str(data[p+1][8]))
#        self.label_amount3.setText(str(data[p+1][9]))
        self.label_paid3.setText(str(data[p+1][9]))
#        self.label_receivable3.setText(str(data[p+1][11]))
        self.textBrowser_payRecord3.setText(str(data[p+1][10]))
        self.label_payRemind3.setText(str(data[p+1][11]))
        self.textBrowser_shipTo3.setText(str(data[p+1][12]))
        self.textBrowser_remark3.setText(str(data[p+1][13]))
        self.label_amount3.setText(str(amount3))
        self.label_receivable3.setText(str(receivable3))


        self.label_id4.setText(str(data[p+2][0])) #数据库是从0开始的，所以减1
        self.label_shipDate4.setText(str(data[p+2][1]))
        self.label_customer4.setText(str(data[p+2][2]))
        self.label_sales4.setText(str(data[p+2][3]))
        self.label_production4.setText(str(data[p+2][4]))
        self.label_model4.setText(str(data[p+2][5]))
        self.label_macID4.setText(str(data[p+2][6]))
        self.label_unitPrice4.setText(str(data[p+2][7]))
        self.label_number4.setText(str(data[p+2][8]))
#        self.label_amount4.setText(str(data[p+2][9]))
        self.label_paid4.setText(str(data[p+2][9]))
#        self.label_receivable4.setText(str(data[p+2][11]))
        self.textBrowser_payRecord4.setText(str(data[p+2][10]))
        self.label_payRemind4.setText(str(data[p+2][11]))
        self.textBrowser_shipTo4.setText(str(data[p+2][12]))
        self.textBrowser_remark4.setText(str(data[p+2][13]))
        self.label_amount4.setText(str(amount4))
        self.label_receivable4.setText(str(receivable4))


        self.label_id5.setText(str(data[p+3][0])) #数据库是从0开始的，所以减1
        self.label_shipDate5.setText(str(data[p+3][1]))
        self.label_customer5.setText(str(data[p+3][2]))
        self.label_sales5.setText(str(data[p+3][3]))
        self.label_production5.setText(str(data[p+3][4]))
        self.label_model5.setText(str(data[p+3][5]))
        self.label_macID5.setText(str(data[p+3][6]))
        self.label_unitPrice5.setText(str(data[p+3][7]))
        self.label_number5.setText(str(data[p+3][8]))
#        self.label_amount5.setText(str(data[p+3][9]))
        self.label_paid5.setText(str(data[p+3][9]))
#        self.label_receivable5.setText(str(data[p+3][11]))
        self.textBrowser_payRecord5.setText(str(data[p+3][10]))
        self.label_payRemind5.setText(str(data[p+3][11]))
        self.textBrowser_shipTo5.setText(str(data[p+3][12]))
        self.textBrowser_remark5.setText(str(data[p+3][13]))
        self.label_amount5.setText(str(amount5))
        self.label_receivable5.setText(str(receivable5))

# 以下设置页面中的当前页/总页数
        self.label_cPage.setText(str(g))
        if dblen%5==0: #如果能被5整除，就说明总记录刚好是5的倍数
            tPage=int(dblen/5)
        else:
            tPage=int(dblen/5+1) #否则，就应该加1页
        self.label_tPage.setText(str(tPage))

    def page(self):
        global g
        g=g+0
        return g

    def dblen(self):
        conn = sqlite3.connect('nextai.db')
        curs = conn.cursor()  #创建游标
        curs.execute("SELECT * from shipment")
        data= curs.fetchall()
        lens=len(data)
        curs.close()  #关闭游标
        conn.commit() #保存数据库
        conn.close() #关闭数据库连接
        return lens

    def reload(self):
        print("shipment_browser:reload start")
        print("g=",NextOffice.shipment.shipment_main.g)
        self.pageDisplay(NextOffice.shipment.shipment_main.g)
        dblen=self.dblen()
        print("shipment_browser:reload finish")

    def jumpTo(self):

        jump_g=str(self.lineEdit_jump.text())
        print("jump start")
        if jump_g=="":
            QMessageBox.critical(self,"注意","输入错误，请输入要跳转到的页码，格式为数字")
            pass
        elif jump_g.isdigit()==False:
            QMessageBox.critical(self,"注意","输入错误，请输入要跳转到的页码，格式为数字")
            pass
        else:
            ttPage=int(self.label_tPage.text())
            jump_gg = int(jump_g)
            if jump_gg > ttPage :
                QMessageBox.critical(self,"注意","输入错误，输入的数字超过最大页码了啊！")
            else:
                self.pageDisplay(jump_gg)


class MyForm ( QWidget, Ui_Form ):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.pushButton_jump.clicked.connect(self.jumpTo)


if __name__=='__main__':
#    global g #全局变量p——当前页面
    g=1
#    dblen=dblen() #获取数据库的总长度，赋值给变量dblen，这样就不需要每次去获取了
    app=QApplication(sys.argv)
    b = MyForm()
    b.pageDisplay(g)
#    b.showBrowser()
    b.show()
    e = NextOffice.shipment.shipment_edit.MyForm()
    a = NextOffice.shipment.shipment_add.MyForm()

    b.pushButton_edit1.clicked.connect(e.handle_click1)
    b.pushButton_edit2.clicked.connect(e.handle_click2)
    b.pushButton_edit3.clicked.connect(e.handle_click3)
    b.pushButton_edit4.clicked.connect(e.handle_click4)
    b.pushButton_edit5.clicked.connect(e.handle_click5)

    b.pushButton_new.clicked.connect(a.handle_click)


    app.exec_()



"""
UIC之后，将以下2个语句中的Main修改为self即可
self.pushButton_next.clicked.connect(self.reloadWidgetAdd)
self.pushButton_previous.clicked.connect(self.reloadWidgetDec)


def dblen():
#        conn = sqlite3.connect('../nextai.db')
        conn = sqlite3.connect('nextai.db')
        curs = conn.cursor()  #创建游标
        curs.execute("SELECT * from shipment")
        data= curs.fetchall()
        lens=len(data)
        print ("开始运行数据库共有记录：",lens)
        curs.close()  #关闭游标
        conn.commit() #保存数据库
        conn.close() #关闭数据库连接
        return lens


"""