# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer_add.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(558, 493)
        Form.setFocusPolicy(QtCore.Qt.StrongFocus)
        Form.setAutoFillBackground(True)
        self.lineEdit_id = QtWidgets.QLineEdit(Form)
        self.lineEdit_id.setGeometry(QtCore.QRect(80, 100, 131, 21))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.textBrowser_contact = QtWidgets.QTextBrowser(Form)
        self.textBrowser_contact.setGeometry(QtCore.QRect(320, 270, 191, 51))
        self.textBrowser_contact.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_contact.setLineWidth(0)
        self.textBrowser_contact.setObjectName("textBrowser_contact")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setGeometry(QtCore.QRect(80, 420, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName("pushButton_save")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 110, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 180, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 210, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 230, 54, 12))
        self.label_5.setObjectName("label_5")
        self.lineEdit_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_name.setGeometry(QtCore.QRect(80, 140, 231, 21))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_nick1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_nick1.setGeometry(QtCore.QRect(80, 170, 231, 21))
        self.lineEdit_nick1.setObjectName("lineEdit_nick1")
        self.lineEdit_nick2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_nick2.setGeometry(QtCore.QRect(80, 200, 231, 21))
        self.lineEdit_nick2.setObjectName("lineEdit_nick2")
        self.lineEdit_nick3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_nick3.setGeometry(QtCore.QRect(80, 230, 231, 21))
        self.lineEdit_nick3.setObjectName("lineEdit_nick3")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 280, 54, 12))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 360, 54, 12))
        self.label_7.setObjectName("label_7")
        self.label_id = QtWidgets.QLabel(Form)
        self.label_id.setGeometry(QtCore.QRect(240, 100, 54, 12))
        self.label_id.setObjectName("label_id")
        self.label_name = QtWidgets.QLabel(Form)
        self.label_name.setGeometry(QtCore.QRect(330, 140, 171, 16))
        self.label_name.setObjectName("label_name")
        self.label_nick1 = QtWidgets.QLabel(Form)
        self.label_nick1.setGeometry(QtCore.QRect(330, 170, 171, 16))
        self.label_nick1.setObjectName("label_nick1")
        self.label_nick2 = QtWidgets.QLabel(Form)
        self.label_nick2.setGeometry(QtCore.QRect(330, 200, 171, 16))
        self.label_nick2.setObjectName("label_nick2")
        self.label_nick3 = QtWidgets.QLabel(Form)
        self.label_nick3.setGeometry(QtCore.QRect(330, 230, 171, 16))
        self.label_nick3.setObjectName("label_nick3")
        self.textBrowser_remark = QtWidgets.QTextBrowser(Form)
        self.textBrowser_remark.setGeometry(QtCore.QRect(320, 350, 191, 51))
        self.textBrowser_remark.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_remark.setLineWidth(0)
        self.textBrowser_remark.setObjectName("textBrowser_remark")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(160, 20, 161, 31))
        self.label_13.setObjectName("label_13")
        self.pushButton_cancel = QtWidgets.QPushButton(Form)
        self.pushButton_cancel.setGeometry(QtCore.QRect(200, 420, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.lineEdit_contact = QtWidgets.QLineEdit(Form)
        self.lineEdit_contact.setGeometry(QtCore.QRect(80, 280, 231, 51))
        self.lineEdit_contact.setObjectName("lineEdit_contact")
        self.lineEdit_remark = QtWidgets.QLineEdit(Form)
        self.lineEdit_remark.setGeometry(QtCore.QRect(80, 350, 231, 51))
        self.lineEdit_remark.setObjectName("lineEdit_remark")

        self.retranslateUi(Form)
        self.pushButton_save.clicked.connect(Form.saveToSqlite)
        self.lineEdit_id.textChanged['QString'].connect(self.label_id.setText)
        self.lineEdit_name.textChanged['QString'].connect(self.label_name.setText)
        self.lineEdit_nick1.textChanged['QString'].connect(self.label_nick1.setText)
        self.lineEdit_nick2.textChanged['QString'].connect(self.label_nick2.setText)
        self.lineEdit_nick3.textChanged['QString'].connect(self.label_nick3.setText)
        self.lineEdit_contact.textChanged['QString'].connect(self.textBrowser_contact.setText)
        self.lineEdit_remark.textChanged['QString'].connect(self.textBrowser_remark.setText)
        self.pushButton_cancel.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_save.setText(_translate("Form", "保存"))
        self.label.setText(_translate("Form", "客户ID"))
        self.label_2.setText(_translate("Form", "客户名称"))
        self.label_3.setText(_translate("Form", "别称1"))
        self.label_4.setText(_translate("Form", "别称2"))
        self.label_5.setText(_translate("Form", "别称3"))
        self.label_6.setText(_translate("Form", "联系方式"))
        self.label_7.setText(_translate("Form", "备注"))
        self.label_id.setText(_translate("Form", "id"))
        self.label_name.setText(_translate("Form", "name"))
        self.label_nick1.setText(_translate("Form", "nick1"))
        self.label_nick2.setText(_translate("Form", "nick2"))
        self.label_nick3.setText(_translate("Form", "nick3"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#aa0000;\">新增客户信息</span></p></body></html>"))
        self.pushButton_cancel.setText(_translate("Form", "取消"))

    def saveToSqlite(self):
        id=str(self.lineEdit_id.text())
        name=str(self.lineEdit_name.text())
        nick1=str(self.lineEdit_nick1.text())
        nick2=str(self.lineEdit_nick2.text())
        nick3=str(self.lineEdit_nick3.text())
        contact=self.textBrowser_contact.toPlainText()
        remark=self.textBrowser_remark.toPlainText()

        print(id,name,nick1,nick2,nick3,contact,remark)


import sys
from PyQt5.QtWidgets import QApplication,QWidget

class myform(QWidget,Ui_Form):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
     #   self.lineEdit.textChanged.connect(self.textBrowser.setText)

if __name__=='__main__':
    app=QApplication(sys.argv)
    w=myform()
    w.show()
    app.exec_()