import sqlite3
import sys
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5.QtWidgets import QMessageBox
import NextOffice.service.service_main
import NextOffice.service.service_edit
import NextOffice.service.service_add

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1311, 809)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(540, 10, 161, 31))
        self.label_13.setObjectName("label_13")
        self.label_id1 = QtWidgets.QLabel(Form)
        self.label_id1.setGeometry(QtCore.QRect(120, 60, 91, 21))
        self.label_id1.setObjectName("label_id1")
        self.lineEdit_search = QtWidgets.QLineEdit(Form)
        self.lineEdit_search.setGeometry(QtCore.QRect(160, 10, 113, 20))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.label_method1 = QtWidgets.QLabel(Form)
        self.label_method1.setGeometry(QtCore.QRect(90, 350, 161, 21))
        self.label_method1.setObjectName("label_method1")
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(10, 80, 251, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.pushButton_SwitchCustomer = QtWidgets.QPushButton(Form)
        self.pushButton_SwitchCustomer.setGeometry(QtCore.QRect(1170, 10, 91, 23))
        self.pushButton_SwitchCustomer.setObjectName("pushButton_SwitchCustomer")
        self.pushButton_edit1 = QtWidgets.QPushButton(Form)
        self.pushButton_edit1.setGeometry(QtCore.QRect(10, 710, 71, 23))
        self.pushButton_edit1.setObjectName("pushButton_edit1")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 368, 51, 41))
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 40, 1291, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_SwitchService = QtWidgets.QPushButton(Form)
        self.pushButton_SwitchService.setGeometry(QtCore.QRect(1070, 10, 91, 23))
        self.pushButton_SwitchService.setObjectName("pushButton_SwitchService")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(130, 12, 31, 20))
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 400, 51, 39))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 61, 39))
        self.label_2.setObjectName("label_2")
        self.pushButton_previous = QtWidgets.QPushButton(Form)
        self.pushButton_previous.setGeometry(QtCore.QRect(120, 770, 75, 23))
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.pushButton_next = QtWidgets.QPushButton(Form)
        self.pushButton_next.setGeometry(QtCore.QRect(230, 770, 75, 23))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_new = QtWidgets.QPushButton(Form)
        self.pushButton_new.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.pushButton_new.setObjectName("pushButton_new")
        self.lineEdit_jump = QtWidgets.QLineEdit(Form)
        self.lineEdit_jump.setGeometry(QtCore.QRect(560, 770, 31, 20))
        self.lineEdit_jump.setObjectName("lineEdit_jump")
        self.pushButton_jump = QtWidgets.QPushButton(Form)
        self.pushButton_jump.setGeometry(QtCore.QRect(620, 770, 41, 21))
        self.pushButton_jump.setObjectName("pushButton_jump")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(520, 760, 91, 39))
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(30, 620, 51, 39))
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(20, 340, 51, 39))
        self.label_14.setObjectName("label_14")
        self.label_name1 = QtWidgets.QLabel(Form)
        self.label_name1.setGeometry(QtCore.QRect(90, 100, 161, 21))
        self.label_name1.setObjectName("label_name1")
        self.label_handlingTime1 = QtWidgets.QLabel(Form)
        self.label_handlingTime1.setGeometry(QtCore.QRect(90, 380, 161, 21))
        self.label_handlingTime1.setObjectName("label_handlingTime1")
        self.label_staff1 = QtWidgets.QLabel(Form)
        self.label_staff1.setGeometry(QtCore.QRect(90, 410, 151, 21))
        self.label_staff1.setObjectName("label_staff1")
        self.textBrowser_problem1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem1.setGeometry(QtCore.QRect(90, 130, 161, 211))
        self.textBrowser_problem1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem1.setLineWidth(0)
        self.textBrowser_problem1.setObjectName("textBrowser_problem1")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(20, 120, 51, 39))
        self.label_21.setObjectName("label_21")
        self.textBrowser_remark1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_remark1.setGeometry(QtCore.QRect(90, 620, 161, 71))
        self.textBrowser_remark1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_remark1.setLineWidth(0)
        self.textBrowser_remark1.setObjectName("textBrowser_remark1")
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(250, 90, 21, 611))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(Form)
        self.line_9.setGeometry(QtCore.QRect(10, 690, 251, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(Form)
        self.line_10.setGeometry(QtCore.QRect(0, 90, 20, 611))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(Form)
        self.line_11.setGeometry(QtCore.QRect(70, 90, 20, 611))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.pushButton_search = QtWidgets.QPushButton(Form)
        self.pushButton_search.setGeometry(QtCore.QRect(280, 10, 41, 21))
        self.pushButton_search.setObjectName("pushButton_search")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(10, 740, 1291, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_SwitchShipment = QtWidgets.QPushButton(Form)
        self.pushButton_SwitchShipment.setGeometry(QtCore.QRect(980, 10, 81, 23))
        self.pushButton_SwitchShipment.setObjectName("pushButton_SwitchShipment")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(360, 760, 141, 39))
        self.label_22.setObjectName("label_22")
        self.label_cPage = QtWidgets.QLabel(Form)
        self.label_cPage.setGeometry(QtCore.QRect(390, 770, 31, 21))
        self.label_cPage.setObjectName("label_cPage")
        self.label_tPage = QtWidgets.QLabel(Form)
        self.label_tPage.setGeometry(QtCore.QRect(440, 770, 31, 21))
        self.label_tPage.setObjectName("label_tPage")
        self.line_29 = QtWidgets.QFrame(Form)
        self.line_29.setGeometry(QtCore.QRect(1290, 90, 21, 611))
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.label_order1 = QtWidgets.QLabel(Form)
        self.label_order1.setGeometry(QtCore.QRect(150, 710, 41, 21))
        self.label_order1.setObjectName("label_order1")
        self.line_27 = QtWidgets.QFrame(Form)
        self.line_27.setGeometry(QtCore.QRect(1290, 90, 21, 611))
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(20, 430, 51, 39))
        self.label_23.setObjectName("label_23")
        self.textBrowser_solution1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_solution1.setGeometry(QtCore.QRect(90, 440, 161, 111))
        self.textBrowser_solution1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_solution1.setLineWidth(0)
        self.textBrowser_solution1.setObjectName("textBrowser_solution1")
        self.label_charge1 = QtWidgets.QLabel(Form)
        self.label_charge1.setGeometry(QtCore.QRect(90, 562, 161, 21))
        self.label_charge1.setObjectName("label_charge1")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(20, 552, 51, 39))
        self.label_15.setObjectName("label_15")
        self.label_classify1 = QtWidgets.QLabel(Form)
        self.label_classify1.setGeometry(QtCore.QRect(90, 592, 161, 21))
        self.label_classify1.setObjectName("label_classify1")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 580, 51, 41))
        self.label_6.setObjectName("label_6")
        self.label_handlingTime2 = QtWidgets.QLabel(Form)
        self.label_handlingTime2.setGeometry(QtCore.QRect(350, 380, 161, 21))
        self.label_handlingTime2.setObjectName("label_handlingTime2")
        self.label_charge2 = QtWidgets.QLabel(Form)
        self.label_charge2.setGeometry(QtCore.QRect(350, 562, 161, 21))
        self.label_charge2.setObjectName("label_charge2")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(290, 620, 51, 39))
        self.label_16.setObjectName("label_16")
        self.line_12 = QtWidgets.QFrame(Form)
        self.line_12.setGeometry(QtCore.QRect(510, 90, 21, 611))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.textBrowser_problem2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem2.setGeometry(QtCore.QRect(350, 130, 161, 211))
        self.textBrowser_problem2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem2.setLineWidth(0)
        self.textBrowser_problem2.setObjectName("textBrowser_problem2")
        self.label_staff2 = QtWidgets.QLabel(Form)
        self.label_staff2.setGeometry(QtCore.QRect(350, 410, 151, 21))
        self.label_staff2.setObjectName("label_staff2")
        self.label_classify2 = QtWidgets.QLabel(Form)
        self.label_classify2.setGeometry(QtCore.QRect(350, 592, 161, 21))
        self.label_classify2.setObjectName("label_classify2")
        self.line_13 = QtWidgets.QFrame(Form)
        self.line_13.setGeometry(QtCore.QRect(270, 690, 251, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_name2 = QtWidgets.QLabel(Form)
        self.label_name2.setGeometry(QtCore.QRect(350, 100, 161, 21))
        self.label_name2.setObjectName("label_name2")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(280, 340, 51, 39))
        self.label_17.setObjectName("label_17")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(280, 368, 51, 41))
        self.label_7.setObjectName("label_7")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(280, 430, 51, 39))
        self.label_24.setObjectName("label_24")
        self.label_method2 = QtWidgets.QLabel(Form)
        self.label_method2.setGeometry(QtCore.QRect(350, 350, 161, 21))
        self.label_method2.setObjectName("label_method2")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(280, 400, 51, 39))
        self.label_10.setObjectName("label_10")
        self.textBrowser_remark2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_remark2.setGeometry(QtCore.QRect(350, 620, 161, 71))
        self.textBrowser_remark2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_remark2.setLineWidth(0)
        self.textBrowser_remark2.setObjectName("textBrowser_remark2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(280, 90, 61, 39))
        self.label_3.setObjectName("label_3")
        self.line_14 = QtWidgets.QFrame(Form)
        self.line_14.setGeometry(QtCore.QRect(270, 80, 251, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(280, 552, 51, 39))
        self.label_18.setObjectName("label_18")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(280, 580, 51, 41))
        self.label_11.setObjectName("label_11")
        self.label_order2 = QtWidgets.QLabel(Form)
        self.label_order2.setGeometry(QtCore.QRect(410, 710, 41, 21))
        self.label_order2.setObjectName("label_order2")
        self.textBrowser_solution2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_solution2.setGeometry(QtCore.QRect(350, 440, 161, 111))
        self.textBrowser_solution2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_solution2.setLineWidth(0)
        self.textBrowser_solution2.setObjectName("textBrowser_solution2")
        self.line_15 = QtWidgets.QFrame(Form)
        self.line_15.setGeometry(QtCore.QRect(260, 90, 20, 611))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.pushButton_edit2 = QtWidgets.QPushButton(Form)
        self.pushButton_edit2.setGeometry(QtCore.QRect(270, 710, 71, 23))
        self.pushButton_edit2.setObjectName("pushButton_edit2")
        self.label_id2 = QtWidgets.QLabel(Form)
        self.label_id2.setGeometry(QtCore.QRect(380, 60, 91, 21))
        self.label_id2.setObjectName("label_id2")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(280, 120, 51, 39))
        self.label_25.setObjectName("label_25")
        self.line_16 = QtWidgets.QFrame(Form)
        self.line_16.setGeometry(QtCore.QRect(330, 90, 20, 611))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.label_handlingTime3 = QtWidgets.QLabel(Form)
        self.label_handlingTime3.setGeometry(QtCore.QRect(610, 380, 161, 21))
        self.label_handlingTime3.setObjectName("label_handlingTime3")
        self.label_charge3 = QtWidgets.QLabel(Form)
        self.label_charge3.setGeometry(QtCore.QRect(610, 562, 161, 21))
        self.label_charge3.setObjectName("label_charge3")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(550, 620, 51, 39))
        self.label_19.setObjectName("label_19")
        self.line_17 = QtWidgets.QFrame(Form)
        self.line_17.setGeometry(QtCore.QRect(770, 90, 21, 611))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.textBrowser_problem3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem3.setGeometry(QtCore.QRect(610, 130, 161, 211))
        self.textBrowser_problem3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem3.setLineWidth(0)
        self.textBrowser_problem3.setObjectName("textBrowser_problem3")
        self.label_staff3 = QtWidgets.QLabel(Form)
        self.label_staff3.setGeometry(QtCore.QRect(610, 410, 151, 21))
        self.label_staff3.setObjectName("label_staff3")
        self.label_classify3 = QtWidgets.QLabel(Form)
        self.label_classify3.setGeometry(QtCore.QRect(610, 592, 161, 21))
        self.label_classify3.setObjectName("label_classify3")
        self.line_18 = QtWidgets.QFrame(Form)
        self.line_18.setGeometry(QtCore.QRect(530, 690, 251, 20))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.label_name3 = QtWidgets.QLabel(Form)
        self.label_name3.setGeometry(QtCore.QRect(610, 100, 161, 21))
        self.label_name3.setObjectName("label_name3")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(540, 340, 51, 39))
        self.label_20.setObjectName("label_20")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(540, 368, 51, 41))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(540, 430, 51, 39))
        self.label_27.setObjectName("label_27")
        self.label_method3 = QtWidgets.QLabel(Form)
        self.label_method3.setGeometry(QtCore.QRect(610, 350, 161, 21))
        self.label_method3.setObjectName("label_method3")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(540, 400, 51, 39))
        self.label_28.setObjectName("label_28")
        self.textBrowser_remark3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_remark3.setGeometry(QtCore.QRect(610, 620, 161, 71))
        self.textBrowser_remark3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_remark3.setLineWidth(0)
        self.textBrowser_remark3.setObjectName("textBrowser_remark3")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(540, 90, 61, 39))
        self.label_29.setObjectName("label_29")
        self.line_19 = QtWidgets.QFrame(Form)
        self.line_19.setGeometry(QtCore.QRect(530, 80, 251, 20))
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(540, 552, 51, 39))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(540, 580, 51, 41))
        self.label_31.setObjectName("label_31")
        self.label_order3 = QtWidgets.QLabel(Form)
        self.label_order3.setGeometry(QtCore.QRect(670, 710, 41, 21))
        self.label_order3.setObjectName("label_order3")
        self.textBrowser_solution3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_solution3.setGeometry(QtCore.QRect(610, 440, 161, 111))
        self.textBrowser_solution3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_solution3.setLineWidth(0)
        self.textBrowser_solution3.setObjectName("textBrowser_solution3")
        self.line_20 = QtWidgets.QFrame(Form)
        self.line_20.setGeometry(QtCore.QRect(520, 90, 20, 611))
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.pushButton_edit3 = QtWidgets.QPushButton(Form)
        self.pushButton_edit3.setGeometry(QtCore.QRect(530, 710, 71, 23))
        self.pushButton_edit3.setObjectName("pushButton_edit3")
        self.label_id3 = QtWidgets.QLabel(Form)
        self.label_id3.setGeometry(QtCore.QRect(640, 60, 91, 21))
        self.label_id3.setObjectName("label_id3")
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setGeometry(QtCore.QRect(540, 120, 51, 39))
        self.label_32.setObjectName("label_32")
        self.line_21 = QtWidgets.QFrame(Form)
        self.line_21.setGeometry(QtCore.QRect(590, 90, 20, 611))
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.label_handlingTime4 = QtWidgets.QLabel(Form)
        self.label_handlingTime4.setGeometry(QtCore.QRect(870, 380, 161, 21))
        self.label_handlingTime4.setObjectName("label_handlingTime4")
        self.label_charge4 = QtWidgets.QLabel(Form)
        self.label_charge4.setGeometry(QtCore.QRect(870, 562, 161, 21))
        self.label_charge4.setObjectName("label_charge4")
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(810, 620, 51, 39))
        self.label_33.setObjectName("label_33")
        self.line_22 = QtWidgets.QFrame(Form)
        self.line_22.setGeometry(QtCore.QRect(1030, 90, 21, 611))
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.textBrowser_problem4 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem4.setGeometry(QtCore.QRect(870, 130, 161, 211))
        self.textBrowser_problem4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem4.setLineWidth(0)
        self.textBrowser_problem4.setObjectName("textBrowser_problem4")
        self.label_staff4 = QtWidgets.QLabel(Form)
        self.label_staff4.setGeometry(QtCore.QRect(870, 410, 151, 21))
        self.label_staff4.setObjectName("label_staff4")
        self.label_classify4 = QtWidgets.QLabel(Form)
        self.label_classify4.setGeometry(QtCore.QRect(870, 592, 161, 21))
        self.label_classify4.setObjectName("label_classify4")
        self.line_23 = QtWidgets.QFrame(Form)
        self.line_23.setGeometry(QtCore.QRect(790, 690, 251, 20))
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.label_name4 = QtWidgets.QLabel(Form)
        self.label_name4.setGeometry(QtCore.QRect(870, 100, 161, 21))
        self.label_name4.setObjectName("label_name4")
        self.label_34 = QtWidgets.QLabel(Form)
        self.label_34.setGeometry(QtCore.QRect(800, 340, 51, 39))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(Form)
        self.label_35.setGeometry(QtCore.QRect(800, 368, 51, 41))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(Form)
        self.label_36.setGeometry(QtCore.QRect(800, 430, 51, 39))
        self.label_36.setObjectName("label_36")
        self.label_method4 = QtWidgets.QLabel(Form)
        self.label_method4.setGeometry(QtCore.QRect(870, 350, 161, 21))
        self.label_method4.setObjectName("label_method4")
        self.label_37 = QtWidgets.QLabel(Form)
        self.label_37.setGeometry(QtCore.QRect(800, 400, 51, 39))
        self.label_37.setObjectName("label_37")
        self.textBrowser_remark4 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_remark4.setGeometry(QtCore.QRect(870, 620, 161, 71))
        self.textBrowser_remark4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_remark4.setLineWidth(0)
        self.textBrowser_remark4.setObjectName("textBrowser_remark4")
        self.label_38 = QtWidgets.QLabel(Form)
        self.label_38.setGeometry(QtCore.QRect(800, 90, 61, 39))
        self.label_38.setObjectName("label_38")
        self.line_24 = QtWidgets.QFrame(Form)
        self.line_24.setGeometry(QtCore.QRect(790, 80, 251, 20))
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.label_39 = QtWidgets.QLabel(Form)
        self.label_39.setGeometry(QtCore.QRect(800, 552, 51, 39))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(Form)
        self.label_40.setGeometry(QtCore.QRect(800, 580, 51, 41))
        self.label_40.setObjectName("label_40")
        self.label_order4 = QtWidgets.QLabel(Form)
        self.label_order4.setGeometry(QtCore.QRect(930, 710, 41, 21))
        self.label_order4.setObjectName("label_order4")
        self.textBrowser_solution4 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_solution4.setGeometry(QtCore.QRect(870, 440, 161, 111))
        self.textBrowser_solution4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_solution4.setLineWidth(0)
        self.textBrowser_solution4.setObjectName("textBrowser_solution4")
        self.line_25 = QtWidgets.QFrame(Form)
        self.line_25.setGeometry(QtCore.QRect(780, 90, 20, 611))
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.pushButton_edit4 = QtWidgets.QPushButton(Form)
        self.pushButton_edit4.setGeometry(QtCore.QRect(790, 710, 71, 23))
        self.pushButton_edit4.setObjectName("pushButton_edit4")
        self.label_id4 = QtWidgets.QLabel(Form)
        self.label_id4.setGeometry(QtCore.QRect(900, 60, 91, 21))
        self.label_id4.setObjectName("label_id4")
        self.label_41 = QtWidgets.QLabel(Form)
        self.label_41.setGeometry(QtCore.QRect(800, 120, 51, 39))
        self.label_41.setObjectName("label_41")
        self.line_26 = QtWidgets.QFrame(Form)
        self.line_26.setGeometry(QtCore.QRect(850, 90, 20, 611))
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.label_handlingTime5 = QtWidgets.QLabel(Form)
        self.label_handlingTime5.setGeometry(QtCore.QRect(1130, 380, 161, 21))
        self.label_handlingTime5.setObjectName("label_handlingTime5")
        self.label_charge5 = QtWidgets.QLabel(Form)
        self.label_charge5.setGeometry(QtCore.QRect(1130, 562, 161, 21))
        self.label_charge5.setObjectName("label_charge5")
        self.label_42 = QtWidgets.QLabel(Form)
        self.label_42.setGeometry(QtCore.QRect(1070, 620, 51, 39))
        self.label_42.setObjectName("label_42")
        self.line_28 = QtWidgets.QFrame(Form)
        self.line_28.setGeometry(QtCore.QRect(1290, 90, 21, 611))
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.textBrowser_problem5 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem5.setGeometry(QtCore.QRect(1130, 130, 161, 211))
        self.textBrowser_problem5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem5.setLineWidth(0)
        self.textBrowser_problem5.setObjectName("textBrowser_problem5")
        self.label_staff5 = QtWidgets.QLabel(Form)
        self.label_staff5.setGeometry(QtCore.QRect(1130, 410, 151, 21))
        self.label_staff5.setObjectName("label_staff5")
        self.label_classify5 = QtWidgets.QLabel(Form)
        self.label_classify5.setGeometry(QtCore.QRect(1130, 592, 161, 21))
        self.label_classify5.setObjectName("label_classify5")
        self.line_30 = QtWidgets.QFrame(Form)
        self.line_30.setGeometry(QtCore.QRect(1050, 690, 251, 20))
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.label_name5 = QtWidgets.QLabel(Form)
        self.label_name5.setGeometry(QtCore.QRect(1130, 100, 161, 21))
        self.label_name5.setObjectName("label_name5")
        self.label_43 = QtWidgets.QLabel(Form)
        self.label_43.setGeometry(QtCore.QRect(1060, 340, 51, 39))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(Form)
        self.label_44.setGeometry(QtCore.QRect(1060, 368, 51, 41))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(Form)
        self.label_45.setGeometry(QtCore.QRect(1060, 430, 51, 39))
        self.label_45.setObjectName("label_45")
        self.label_method5 = QtWidgets.QLabel(Form)
        self.label_method5.setGeometry(QtCore.QRect(1130, 350, 161, 21))
        self.label_method5.setObjectName("label_method5")
        self.label_46 = QtWidgets.QLabel(Form)
        self.label_46.setGeometry(QtCore.QRect(1060, 400, 51, 39))
        self.label_46.setObjectName("label_46")
        self.textBrowser_remark5 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_remark5.setGeometry(QtCore.QRect(1130, 620, 161, 71))
        self.textBrowser_remark5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_remark5.setLineWidth(0)
        self.textBrowser_remark5.setObjectName("textBrowser_remark5")
        self.label_47 = QtWidgets.QLabel(Form)
        self.label_47.setGeometry(QtCore.QRect(1060, 90, 61, 39))
        self.label_47.setObjectName("label_47")
        self.line_31 = QtWidgets.QFrame(Form)
        self.line_31.setGeometry(QtCore.QRect(1050, 80, 251, 20))
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.label_48 = QtWidgets.QLabel(Form)
        self.label_48.setGeometry(QtCore.QRect(1060, 552, 51, 39))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(Form)
        self.label_49.setGeometry(QtCore.QRect(1060, 580, 51, 41))
        self.label_49.setObjectName("label_49")
        self.label_order5 = QtWidgets.QLabel(Form)
        self.label_order5.setGeometry(QtCore.QRect(1190, 710, 41, 21))
        self.label_order5.setObjectName("label_order5")
        self.textBrowser_solution5 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_solution5.setGeometry(QtCore.QRect(1130, 440, 161, 111))
        self.textBrowser_solution5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_solution5.setLineWidth(0)
        self.textBrowser_solution5.setObjectName("textBrowser_solution5")
        self.line_32 = QtWidgets.QFrame(Form)
        self.line_32.setGeometry(QtCore.QRect(1040, 90, 20, 611))
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.pushButton_edit5 = QtWidgets.QPushButton(Form)
        self.pushButton_edit5.setGeometry(QtCore.QRect(1050, 710, 71, 23))
        self.pushButton_edit5.setObjectName("pushButton_edit5")
        self.label_id5 = QtWidgets.QLabel(Form)
        self.label_id5.setGeometry(QtCore.QRect(1160, 60, 91, 21))
        self.label_id5.setObjectName("label_id5")
        self.label_50 = QtWidgets.QLabel(Form)
        self.label_50.setGeometry(QtCore.QRect(1060, 120, 51, 39))
        self.label_50.setObjectName("label_50")
        self.line_33 = QtWidgets.QFrame(Form)
        self.line_33.setGeometry(QtCore.QRect(1110, 90, 20, 611))
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.label_13.raise_()
        self.label_id1.raise_()
        self.lineEdit_search.raise_()
        self.label_method1.raise_()
        self.line_7.raise_()
        self.pushButton_SwitchCustomer.raise_()
        self.pushButton_edit1.raise_()
        self.label_4.raise_()
        self.line.raise_()
        self.pushButton_SwitchService.raise_()
        self.label_8.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.pushButton_previous.raise_()
        self.pushButton_next.raise_()
        self.pushButton_new.raise_()
        self.pushButton_jump.raise_()
        self.label_9.raise_()
        self.lineEdit_jump.raise_()
        self.label_12.raise_()
        self.label_14.raise_()
        self.label_name1.raise_()
        self.label_handlingTime1.raise_()
        self.label_staff1.raise_()
        self.textBrowser_problem1.raise_()
        self.label_21.raise_()
        self.textBrowser_remark1.raise_()
        self.line_8.raise_()
        self.line_9.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        self.pushButton_search.raise_()
        self.line_2.raise_()
        self.pushButton_SwitchShipment.raise_()
        self.label_22.raise_()
        self.label_cPage.raise_()
        self.label_tPage.raise_()
        self.line_29.raise_()
        self.label_order1.raise_()
        self.line_27.raise_()
        self.label_23.raise_()
        self.textBrowser_solution1.raise_()
        self.label_charge1.raise_()
        self.label_15.raise_()
        self.label_classify1.raise_()
        self.label_6.raise_()
        self.label_handlingTime2.raise_()
        self.label_charge2.raise_()
        self.label_16.raise_()
        self.line_12.raise_()
        self.textBrowser_problem2.raise_()
        self.label_staff2.raise_()
        self.label_classify2.raise_()
        self.line_13.raise_()
        self.label_name2.raise_()
        self.label_17.raise_()
        self.label_7.raise_()
        self.label_24.raise_()
        self.label_method2.raise_()
        self.label_10.raise_()
        self.textBrowser_remark2.raise_()
        self.label_3.raise_()
        self.line_14.raise_()
        self.label_18.raise_()
        self.label_11.raise_()
        self.label_order2.raise_()
        self.textBrowser_solution2.raise_()
        self.line_15.raise_()
        self.pushButton_edit2.raise_()
        self.label_id2.raise_()
        self.label_25.raise_()
        self.line_16.raise_()
        self.label_handlingTime3.raise_()
        self.label_charge3.raise_()
        self.label_19.raise_()
        self.line_17.raise_()
        self.textBrowser_problem3.raise_()
        self.label_staff3.raise_()
        self.label_classify3.raise_()
        self.line_18.raise_()
        self.label_name3.raise_()
        self.label_20.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.label_method3.raise_()
        self.label_28.raise_()
        self.textBrowser_remark3.raise_()
        self.label_29.raise_()
        self.line_19.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.label_order3.raise_()
        self.textBrowser_solution3.raise_()
        self.line_20.raise_()
        self.pushButton_edit3.raise_()
        self.label_id3.raise_()
        self.label_32.raise_()
        self.line_21.raise_()
        self.label_handlingTime4.raise_()
        self.label_charge4.raise_()
        self.label_33.raise_()
        self.line_22.raise_()
        self.textBrowser_problem4.raise_()
        self.label_staff4.raise_()
        self.label_classify4.raise_()
        self.line_23.raise_()
        self.label_name4.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_method4.raise_()
        self.label_37.raise_()
        self.textBrowser_remark4.raise_()
        self.label_38.raise_()
        self.line_24.raise_()
        self.label_39.raise_()
        self.label_40.raise_()
        self.label_order4.raise_()
        self.textBrowser_solution4.raise_()
        self.line_25.raise_()
        self.pushButton_edit4.raise_()
        self.label_id4.raise_()
        self.label_41.raise_()
        self.line_26.raise_()
        self.label_handlingTime5.raise_()
        self.label_charge5.raise_()
        self.label_42.raise_()
        self.line_28.raise_()
        self.textBrowser_problem5.raise_()
        self.label_staff5.raise_()
        self.label_classify5.raise_()
        self.line_30.raise_()
        self.label_name5.raise_()
        self.label_43.raise_()
        self.label_44.raise_()
        self.label_45.raise_()
        self.label_method5.raise_()
        self.label_46.raise_()
        self.textBrowser_remark5.raise_()
        self.label_47.raise_()
        self.line_31.raise_()
        self.label_48.raise_()
        self.label_49.raise_()
        self.label_order5.raise_()
        self.textBrowser_solution5.raise_()
        self.line_32.raise_()
        self.pushButton_edit5.raise_()
        self.label_id5.raise_()
        self.label_50.raise_()
        self.line_33.raise_()

        self.retranslateUi(Form)
        self.pushButton_previous.clicked.connect(self.reloadWidgetDec)
        self.pushButton_next.clicked.connect(self.reloadWidgetAdd)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#0b3da8;\">售后信息浏览</span></p></body></html>"))
        self.label_id1.setText(_translate("Form", "serviceID"))
        self.label_method1.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.pushButton_SwitchCustomer.setText(_translate("Form", "客户信息界面"))
        self.pushButton_edit1.setText(_translate("Form", "编辑"))
        self.label_4.setText(_translate("Form", "处理时间"))
        self.pushButton_SwitchService.setText(_translate("Form", "售后服务记录"))
        self.label_8.setText(_translate("Form", "搜索"))
        self.label_5.setText(_translate("Form", "处理人员"))
        self.label_2.setText(_translate("Form", "客户名称"))
        self.pushButton_previous.setText(_translate("Form", "上一页"))
        self.pushButton_next.setText(_translate("Form", "下一页"))
        self.pushButton_new.setText(_translate("Form", "新增售后信息"))
        self.pushButton_jump.setText(_translate("Form", "GO!"))
        self.label_9.setText(_translate("Form", "跳到第       页"))
        self.label_12.setText(_translate("Form", "备注"))
        self.label_14.setText(_translate("Form", "处理方式"))
        self.label_name1.setText(_translate("Form", "name"))
        self.label_handlingTime1.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_staff1.setText(_translate("Form", "staff"))
        self.textBrowser_problem1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_21.setText(_translate("Form", "反馈问题"))
        self.textBrowser_remark1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">remark</p></body></html>"))
        self.pushButton_search.setText(_translate("Form", "GO!"))
        self.pushButton_SwitchShipment.setText(_translate("Form", "产品出货信息"))
        self.label_22.setText(_translate("Form", "第        /         页"))
        self.label_cPage.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#063661;\">cPage</span></p></body></html>"))
        self.label_tPage.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#063661;\">tPage</span></p></body></html>"))
        self.label_order1.setText(_translate("Form", "order"))
        self.label_23.setText(_translate("Form", "解决方法"))
        self.textBrowser_solution1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">solution</p></body></html>"))
        self.label_charge1.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.label_15.setText(_translate("Form", "收费金额"))
        self.label_classify1.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.label_6.setText(_translate("Form", "问题归类"))
        self.label_handlingTime2.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_charge2.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.label_16.setText(_translate("Form", "备注"))
        self.textBrowser_problem2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_staff2.setText(_translate("Form", "staff"))
        self.label_classify2.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.label_name2.setText(_translate("Form", "name"))
        self.label_17.setText(_translate("Form", "处理方式"))
        self.label_7.setText(_translate("Form", "处理时间"))
        self.label_24.setText(_translate("Form", "解决方法"))
        self.label_method2.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.label_10.setText(_translate("Form", "处理人员"))
        self.textBrowser_remark2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">remark</p></body></html>"))
        self.label_3.setText(_translate("Form", "客户名称"))
        self.label_18.setText(_translate("Form", "收费金额"))
        self.label_11.setText(_translate("Form", "问题归类"))
        self.label_order2.setText(_translate("Form", "order"))
        self.textBrowser_solution2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">solution</p></body></html>"))
        self.pushButton_edit2.setText(_translate("Form", "编辑"))
        self.label_id2.setText(_translate("Form", "serviceID"))
        self.label_25.setText(_translate("Form", "反馈问题"))
        self.label_handlingTime3.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_charge3.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.label_19.setText(_translate("Form", "备注"))
        self.textBrowser_problem3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_staff3.setText(_translate("Form", "staff"))
        self.label_classify3.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.label_name3.setText(_translate("Form", "name"))
        self.label_20.setText(_translate("Form", "处理方式"))
        self.label_26.setText(_translate("Form", "处理时间"))
        self.label_27.setText(_translate("Form", "解决方法"))
        self.label_method3.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.label_28.setText(_translate("Form", "处理人员"))
        self.textBrowser_remark3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">remark</p></body></html>"))
        self.label_29.setText(_translate("Form", "客户名称"))
        self.label_30.setText(_translate("Form", "收费金额"))
        self.label_31.setText(_translate("Form", "问题归类"))
        self.label_order3.setText(_translate("Form", "order"))
        self.textBrowser_solution3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">solution</p></body></html>"))
        self.pushButton_edit3.setText(_translate("Form", "编辑"))
        self.label_id3.setText(_translate("Form", "serviceID"))
        self.label_32.setText(_translate("Form", "反馈问题"))
        self.label_handlingTime4.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_charge4.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.label_33.setText(_translate("Form", "备注"))
        self.textBrowser_problem4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_staff4.setText(_translate("Form", "staff"))
        self.label_classify4.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.label_name4.setText(_translate("Form", "name"))
        self.label_34.setText(_translate("Form", "处理方式"))
        self.label_35.setText(_translate("Form", "处理时间"))
        self.label_36.setText(_translate("Form", "解决方法"))
        self.label_method4.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.label_37.setText(_translate("Form", "处理人员"))
        self.textBrowser_remark4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">remark</p></body></html>"))
        self.label_38.setText(_translate("Form", "客户名称"))
        self.label_39.setText(_translate("Form", "收费金额"))
        self.label_40.setText(_translate("Form", "问题归类"))
        self.label_order4.setText(_translate("Form", "order"))
        self.textBrowser_solution4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">solution</p></body></html>"))
        self.pushButton_edit4.setText(_translate("Form", "编辑"))
        self.label_id4.setText(_translate("Form", "serviceID"))
        self.label_41.setText(_translate("Form", "反馈问题"))
        self.label_handlingTime5.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_charge5.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.label_42.setText(_translate("Form", "备注"))
        self.textBrowser_problem5.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_staff5.setText(_translate("Form", "staff"))
        self.label_classify5.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.label_name5.setText(_translate("Form", "name"))
        self.label_43.setText(_translate("Form", "处理方式"))
        self.label_44.setText(_translate("Form", "处理时间"))
        self.label_45.setText(_translate("Form", "解决方法"))
        self.label_method5.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.label_46.setText(_translate("Form", "处理人员"))
        self.textBrowser_remark5.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">remark</p></body></html>"))
        self.label_47.setText(_translate("Form", "客户名称"))
        self.label_48.setText(_translate("Form", "收费金额"))
        self.label_49.setText(_translate("Form", "问题归类"))
        self.label_order5.setText(_translate("Form", "order"))
        self.textBrowser_solution5.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">solution</p></body></html>"))
        self.pushButton_edit5.setText(_translate("Form", "编辑"))
        self.label_id5.setText(_translate("Form", "serviceID"))
        self.label_50.setText(_translate("Form", "反馈问题"))

####以上为QTDesiger自动生成代码
###以下为自己写的代码
    def closeEvent(self, event):        #关闭窗口触发以下事件
        reply = QMessageBox.question(self, '消息提示', '你确定要退出吗?', QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
        if reply == QMessageBox.Yes:
            event.accept()        #接受关闭事件
        else:
            event.ignore()        #忽略关闭事件

    def reloadWidgetAdd(self,i): #点击下一页触发
        print ("reloadWidgeAdd")
        i= int(self.label_order5.text())
        if i < self.dblen():
#            global g
            NextOffice.service.service_main.g=NextOffice.service.service_main.g+1 #全局变量P页数+1
            self.pageDisplay(NextOffice.service.service_main.g)
            print("service_main的g是",NextOffice.service.service_main.g)

        else:
            print("remain")
    def reloadWidgetDec(self,i): #点击上一页触发
        print ("reloadWidgeDec")
        i= int(self.label_order5.text())
        if i > 5:
            global g
            NextOffice.service.service_main.g=NextOffice.service.service_main.g-1 #全局变量P页数+1
#            g=g-1 #全局变量P页数-1
            self.pageDisplay(NextOffice.service.service_main.g)
        else:
            print("remain")
    def pageDisplay(self,g):  #本函数显示g页的数据
        self.pushButton_edit2.show() #显示开始，先把之前可能隐藏的按钮重新显示出来
        self.pushButton_edit3.show()
        self.pushButton_edit4.show()
        self.pushButton_edit5.show()
        self.pushButton_edit6.show()
        self.pushButton_edit7.show()
        self.pushButton_edit8.show()
        self.pushButton_edit9.show()
        self.pushButton_edit10.show()

        self.pushButton_detail2.show()#显示开始，先把之前可能隐藏的按钮重新显示出来
        self.pushButton_detail3.show()
        self.pushButton_detail4.show()
        self.pushButton_detail5.show()
        self.pushButton_detail6.show()
        self.pushButton_detail7.show()
        self.pushButton_detail8.show()
        self.pushButton_detail9.show()
        self.pushButton_detail10.show()

        print("service_browser: pageDisplay",g)
        orderJ=g*10
        orderI=orderJ-1
        orderH=orderJ-2
        orderG=orderJ-3
        orderF=orderJ-4
        orderE=orderJ-5
        orderD=orderJ-6
        orderC=orderJ-7
        orderB=orderJ-8
        orderA=orderJ-9
        self.label_order1.setText(str(orderA))
        self.label_order2.setText(str(orderB))
        self.label_order3.setText(str(orderC))
        self.label_order4.setText(str(orderD))
        self.label_order5.setText(str(orderE))
        self.label_order6.setText(str(orderF))
        self.label_order7.setText(str(orderG))
        self.label_order8.setText(str(orderH))
        self.label_order9.setText(str(orderI))
        self.label_order10.setText(str(orderJ))

        conn = sqlite3.connect('nextai.db')
        curs = conn.cursor()  #创建游标
#        print ("pageData()打开数据库成功")
        curs.execute("SELECT * from service")
        data= curs.fetchall() #将数据库全部数据读入data中
        curs.close()  #关闭游标
        conn.commit() #保存数据库
        conn.close() #关闭数据库连接

        p=g*5-4  #获得当前页面的第1行

        blank=["","","","","","","","","",""]
        dblen=self.dblen()
        print("service_browser-pageDisplay:现在数据库中共有记录：",dblen)

        a=dblen%5 #计算最后一页总共有几行？
        b=5-a  #计算空白的有几行
        while b>0:#将当前页面的空白记录行填充N/A，以免data赋值的时候不够5行导致出错
            data.append(blank)
            if g == dblen//5+1:  #如果当前页面是最后一页---总页数/5然后+1
                if b==1: #如果只有1行空白
                    self.pushButton_edit5.hide() #隐藏最后一个编辑按钮
                elif b==2:#如果有2行空白
                    self.pushButton_edit4.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit5.hide()
                elif b==3:#如果有3行空白
                    self.pushButton_edit3.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit4.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit5.hide()
                elif b==4:#如果有4行空白
                    self.pushButton_edit2.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit3.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit4.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit5.hide()
            b=b-1

#以下将数据库中获取的内容分别对应显示在5行内
        self.label_id1.setText(str(data[p-1][0])) #数据库是从0开始的，所以减1
        self.label_name1.setText(str(data[p-1][1]))
        self.textBrowser_problem1.setText(str(data[p-1][2]))
        self.label_method1.setText(str(data[p-1][3]))
        self.label_handlingTime1.setText(str(data[p-1][4]))
        self.label_staff1.setText(str(data[p-1][5]))
        self.textBrowser_solution1.setText(str(data[p-1][6]))
        self.label_charge1.setText(str(data[p-1][7]))
        self.label_classify1.setText(str(data[p-1][8]))
        self.textBrowser_remark1.setText(str(data[p-1][9]))

        self.label_id2.setText(str(data[p][0]))
        self.label_name2.setText(str(data[p][1]))
        self.textBrowser_problem2.setText(str(data[p][2]))
        self.label_method2.setText(str(data[p][3]))
        self.label_handlingTime2.setText(str(data[p][4]))
        self.label_staff2.setText(str(data[p][5]))
        self.textBrowser_solution2.setText(str(data[p][6]))
        self.label_charge2.setText(str(data[p][7]))
        self.label_classify2.setText(str(data[p][8]))
        self.textBrowser_remark2.setText(str(data[p][9]))

        self.label_id3.setText(str(data[p+1][0]))
        self.label_name3.setText(str(data[p+1][1]))
        self.textBrowser_problem3.setText(str(data[p+1][2]))
        self.label_method3.setText(str(data[p+1][3]))
        self.label_handlingTime3.setText(str(data[p+1][4]))
        self.label_staff3.setText(str(data[p+1][5]))
        self.textBrowser_solution3.setText(str(data[p+1][6]))
        self.label_charge3.setText(str(data[p+1][7]))
        self.label_classify3.setText(str(data[p+1][8]))
        self.textBrowser_remark3.setText(str(data[p+1][9]))

        self.label_id4.setText(str(data[p+2][0]))
        self.label_name4.setText(str(data[p+2][1]))
        self.textBrowser_problem4.setText(str(data[p+2][2]))
        self.label_method4.setText(str(data[p+2][3]))
        self.label_handlingTime4.setText(str(data[p+2][4]))
        self.label_staff4.setText(str(data[p+2][5]))
        self.textBrowser_solution4.setText(str(data[p+2][6]))
        self.label_charge4.setText(str(data[p+2][7]))
        self.label_classify4.setText(str(data[p+2][8]))
        self.textBrowser_remark4.setText(str(data[p+2][9]))

        self.label_id5.setText(str(data[p+3][0]))
        self.label_name5.setText(str(data[p+3][1]))
        self.textBrowser_problem5.setText(str(data[p+3][2]))
        self.label_method5.setText(str(data[p+3][3]))
        self.label_handlingTime5.setText(str(data[p+3][4]))
        self.label_staff5.setText(str(data[p+3][5]))
        self.textBrowser_solution5.setText(str(data[p+3][6]))
        self.label_charge5.setText(str(data[p+3][7]))
        self.label_classify5.setText(str(data[p+3][8]))
        self.textBrowser_remark5.setText(str(data[p+3][9]))

# 以下设置页面中的当前页/总页数
        self.label_cPage.setText(str(g))
        if dblen%5==0: #如果能被5整除，就说明总记录刚好是5的倍数
            tPage=int(dblen/5)
        else:
            tPage=int(dblen/5+1) #否则，就应该加1页
        self.label_tPage.setText(str(tPage))

    def page(self):
        global g
        g=g+0
        return g
    def reload(self):
        print("browser:reload start")
        print("g=",NextOffice.service.service_main.g)
        print("???")
        self.pageDisplay(NextOffice.service.service_main.g)
        print("browser:reload finish")
    def dblen(self):
        conn = sqlite3.connect('nextai.db')
        curs = conn.cursor()  #创建游标
#        print ("打开数据库成功")

        curs.execute("SELECT * from service")
        data= curs.fetchall()
#        print (data[10])
        print (data[0][7])
#        print (data[0][1])

        lens=len(data)
        print ("开始运行数据库共有记录：",lens)

        curs.close()  #关闭游标
        conn.commit() #保存数据库
        conn.close() #关闭数据库连接
        return lens
    def jumpTo(self):

        jump_g=str(self.lineEdit_jump.text())
        print("jump start")
        if jump_g=="":
            QMessageBox.critical(self,"注意","输入错误，请输入要跳转到的页码，格式为数字")
            pass
        elif jump_g.isdigit()==False:
            QMessageBox.critical(self,"注意","输入错误，请输入要跳转到的页码，格式为数字")
            pass
        else:
            ttPage=int(self.label_tPage.text())
            jump_gg = int(jump_g)
            if jump_gg > ttPage :
                QMessageBox.critical(self,"注意","输入错误，输入的数字超过最大页码了啊！")
            else:
                self.pageDisplay(jump_gg)


class MyForm ( QWidget, Ui_Form ):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.pushButton_jump.clicked.connect(self.jumpTo)


if __name__=='__main__':
#    global g #全局变量p——当前页面
    g=1
#    dblen=dblen() #获取数据库的总长度，赋值给变量dblen，这样就不需要每次去获取了
    app=QApplication(sys.argv)
    w = MyForm()
    w.pageDisplay(1)
    w.show()
    a = NextOffice.service.service_edit.MyForm()
    w.pushButton_edit1.clicked.connect(a.handle_click1)
    w.pushButton_edit2.clicked.connect(a.handle_click2)
    w.pushButton_edit3.clicked.connect(a.handle_click3)
    w.pushButton_edit4.clicked.connect(a.handle_click4)
    w.pushButton_edit5.clicked.connect(a.handle_click5)

    app.exec_()



"""
UIC之后，将以下2个语句中的Main修改为self即可
self.pushButton_next.clicked.connect(self.reloadWidgetAdd)
self.pushButton_previous.clicked.connect(self.reloadWidgetDec)

"""
