import sqlite3
import sys
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5.QtWidgets import QMessageBox
import service_edit
import service_add
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1213, 689)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(470, 10, 161, 61))
        self.label_13.setObjectName("label_13")
        self.lineEdit_search = QtWidgets.QLineEdit(Form)
        self.lineEdit_search.setGeometry(QtCore.QRect(80, 20, 113, 20))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.label_name1 = QtWidgets.QLabel(Form)
        self.label_name1.setGeometry(QtCore.QRect(160, 150, 251, 21))
        self.label_name1.setObjectName("label_name1")
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(50, 70, 1061, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.pushButton_SwitchCustomer = QtWidgets.QPushButton(Form)
        self.pushButton_SwitchCustomer.setGeometry(QtCore.QRect(1020, 20, 91, 23))
        self.pushButton_SwitchCustomer.setObjectName("pushButton_SwitchCustomer")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(560, 90, 91, 39))
        self.label_4.setObjectName("label_4")
        self.pushButton_SwitchService = QtWidgets.QPushButton(Form)
        self.pushButton_SwitchService.setGeometry(QtCore.QRect(920, 20, 91, 23))
        self.pushButton_SwitchService.setObjectName("pushButton_SwitchService")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(50, 22, 31, 20))
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(820, 90, 61, 39))
        self.label_5.setObjectName("label_5")
        self.pushButton_previous = QtWidgets.QPushButton(Form)
        self.pushButton_previous.setGeometry(QtCore.QRect(350, 650, 75, 23))
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.pushButton_next = QtWidgets.QPushButton(Form)
        self.pushButton_next.setGeometry(QtCore.QRect(460, 650, 75, 23))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_new = QtWidgets.QPushButton(Form)
        self.pushButton_new.setGeometry(QtCore.QRect(50, 650, 91, 23))
        self.pushButton_new.setObjectName("pushButton_new")
        self.lineEdit_jump = QtWidgets.QLineEdit(Form)
        self.lineEdit_jump.setGeometry(QtCore.QRect(790, 650, 31, 20))
        self.lineEdit_jump.setObjectName("lineEdit_jump")
        self.pushButton_jump = QtWidgets.QPushButton(Form)
        self.pushButton_jump.setGeometry(QtCore.QRect(850, 650, 41, 21))
        self.pushButton_jump.setObjectName("pushButton_jump")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(750, 640, 91, 39))
        self.label_9.setObjectName("label_9")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(260, 90, 71, 39))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(70, 90, 71, 39))
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(910, 90, 61, 39))
        self.label_17.setObjectName("label_17")
        self.line_11 = QtWidgets.QFrame(Form)
        self.line_11.setGeometry(QtCore.QRect(40, 140, 20, 41))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.pushButton_search = QtWidgets.QPushButton(Form)
        self.pushButton_search.setGeometry(QtCore.QRect(200, 20, 41, 21))
        self.pushButton_search.setObjectName("pushButton_search")
        self.pushButton_SwitchShipment = QtWidgets.QPushButton(Form)
        self.pushButton_SwitchShipment.setGeometry(QtCore.QRect(830, 20, 81, 23))
        self.pushButton_SwitchShipment.setObjectName("pushButton_SwitchShipment")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(590, 640, 141, 39))
        self.label_22.setObjectName("label_22")
        self.label_cPage = QtWidgets.QLabel(Form)
        self.label_cPage.setGeometry(QtCore.QRect(610, 650, 41, 21))
        self.label_cPage.setObjectName("label_cPage")
        self.label_tPage = QtWidgets.QLabel(Form)
        self.label_tPage.setGeometry(QtCore.QRect(660, 650, 41, 21))
        self.label_tPage.setObjectName("label_tPage")
        self.label_order1 = QtWidgets.QLabel(Form)
        self.label_order1.setGeometry(QtCore.QRect(10, 150, 31, 21))
        self.label_order1.setObjectName("label_order1")
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(50, 130, 1061, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_12 = QtWidgets.QFrame(Form)
        self.line_12.setGeometry(QtCore.QRect(50, 170, 1061, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(Form)
        self.line_13.setGeometry(QtCore.QRect(410, 140, 20, 41))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(Form)
        self.line_14.setGeometry(QtCore.QRect(140, 140, 20, 41))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(Form)
        self.line_15.setGeometry(QtCore.QRect(780, 140, 20, 41))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(Form)
        self.line_16.setGeometry(QtCore.QRect(900, 140, 20, 41))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_22 = QtWidgets.QFrame(Form)
        self.line_22.setGeometry(QtCore.QRect(1100, 140, 20, 41))
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.label_order2 = QtWidgets.QLabel(Form)
        self.label_order2.setGeometry(QtCore.QRect(10, 200, 31, 21))
        self.label_order2.setObjectName("label_order2")
        self.label_order3 = QtWidgets.QLabel(Form)
        self.label_order3.setGeometry(QtCore.QRect(10, 250, 31, 21))
        self.label_order3.setObjectName("label_order3")
        self.label_order4 = QtWidgets.QLabel(Form)
        self.label_order4.setGeometry(QtCore.QRect(10, 300, 31, 21))
        self.label_order4.setObjectName("label_order4")
        self.label_order5 = QtWidgets.QLabel(Form)
        self.label_order5.setGeometry(QtCore.QRect(10, 350, 31, 21))
        self.label_order5.setObjectName("label_order5")
        self.label_order6 = QtWidgets.QLabel(Form)
        self.label_order6.setGeometry(QtCore.QRect(10, 400, 31, 21))
        self.label_order6.setObjectName("label_order6")
        self.label_order7 = QtWidgets.QLabel(Form)
        self.label_order7.setGeometry(QtCore.QRect(10, 450, 31, 21))
        self.label_order7.setObjectName("label_order7")
        self.label_order8 = QtWidgets.QLabel(Form)
        self.label_order8.setGeometry(QtCore.QRect(10, 500, 31, 21))
        self.label_order8.setObjectName("label_order8")
        self.label_order9 = QtWidgets.QLabel(Form)
        self.label_order9.setGeometry(QtCore.QRect(10, 550, 31, 21))
        self.label_order9.setObjectName("label_order9")
        self.label_order10 = QtWidgets.QLabel(Form)
        self.label_order10.setGeometry(QtCore.QRect(10, 600, 31, 21))
        self.label_order10.setObjectName("label_order10")
        self.pushButton_advSearch = QtWidgets.QPushButton(Form)
        self.pushButton_advSearch.setGeometry(QtCore.QRect(250, 20, 91, 21))
        self.pushButton_advSearch.setObjectName("pushButton_advSearch")
        self.line_149 = QtWidgets.QFrame(Form)
        self.line_149.setGeometry(QtCore.QRect(40, 80, 20, 51))
        self.line_149.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_149.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_149.setObjectName("line_149")
        self.line_150 = QtWidgets.QFrame(Form)
        self.line_150.setGeometry(QtCore.QRect(1100, 80, 20, 51))
        self.line_150.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_150.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_150.setObjectName("line_150")
        self.pushButton_ProblemSource = QtWidgets.QPushButton(Form)
        self.pushButton_ProblemSource.setGeometry(QtCore.QRect(150, 650, 81, 23))
        self.pushButton_ProblemSource.setObjectName("pushButton_ProblemSource")
        self.line_23 = QtWidgets.QFrame(Form)
        self.line_23.setGeometry(QtCore.QRect(960, 140, 20, 41))
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(1010, 90, 71, 39))
        self.label_18.setObjectName("label_18")
        self.textBrowser_problem1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem1.setGeometry(QtCore.QRect(420, 140, 371, 41))
        self.textBrowser_problem1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem1.setLineWidth(0)
        self.textBrowser_problem1.setObjectName("textBrowser_problem1")
        self.label_handlingTime1 = QtWidgets.QLabel(Form)
        self.label_handlingTime1.setGeometry(QtCore.QRect(60, 150, 101, 21))
        self.label_handlingTime1.setObjectName("label_handlingTime1")
        self.label_method1 = QtWidgets.QLabel(Form)
        self.label_method1.setGeometry(QtCore.QRect(800, 150, 101, 21))
        self.label_method1.setObjectName("label_method1")
        self.label_charge1 = QtWidgets.QLabel(Form)
        self.label_charge1.setGeometry(QtCore.QRect(920, 150, 51, 21))
        self.label_charge1.setObjectName("label_charge1")
        self.label_classify1 = QtWidgets.QLabel(Form)
        self.label_classify1.setGeometry(QtCore.QRect(980, 150, 121, 21))
        self.label_classify1.setObjectName("label_classify1")
        self.textBrowser_problem2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem2.setGeometry(QtCore.QRect(420, 190, 371, 41))
        self.textBrowser_problem2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem2.setLineWidth(0)
        self.textBrowser_problem2.setObjectName("textBrowser_problem2")
        self.label_method2 = QtWidgets.QLabel(Form)
        self.label_method2.setGeometry(QtCore.QRect(800, 200, 101, 21))
        self.label_method2.setObjectName("label_method2")
        self.label_classify2 = QtWidgets.QLabel(Form)
        self.label_classify2.setGeometry(QtCore.QRect(980, 200, 121, 21))
        self.label_classify2.setObjectName("label_classify2")
        self.label_name2 = QtWidgets.QLabel(Form)
        self.label_name2.setGeometry(QtCore.QRect(160, 200, 251, 21))
        self.label_name2.setObjectName("label_name2")
        self.line_9 = QtWidgets.QFrame(Form)
        self.line_9.setGeometry(QtCore.QRect(50, 180, 1061, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_17 = QtWidgets.QFrame(Form)
        self.line_17.setGeometry(QtCore.QRect(900, 190, 20, 41))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.label_handlingTime2 = QtWidgets.QLabel(Form)
        self.label_handlingTime2.setGeometry(QtCore.QRect(60, 200, 101, 21))
        self.label_handlingTime2.setObjectName("label_handlingTime2")
        self.line_18 = QtWidgets.QFrame(Form)
        self.line_18.setGeometry(QtCore.QRect(780, 190, 20, 41))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_24 = QtWidgets.QFrame(Form)
        self.line_24.setGeometry(QtCore.QRect(960, 190, 20, 41))
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.line_19 = QtWidgets.QFrame(Form)
        self.line_19.setGeometry(QtCore.QRect(410, 190, 20, 41))
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_25 = QtWidgets.QFrame(Form)
        self.line_25.setGeometry(QtCore.QRect(1100, 190, 20, 41))
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.line_20 = QtWidgets.QFrame(Form)
        self.line_20.setGeometry(QtCore.QRect(40, 190, 20, 41))
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.line_21 = QtWidgets.QFrame(Form)
        self.line_21.setGeometry(QtCore.QRect(140, 190, 20, 41))
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.label_charge2 = QtWidgets.QLabel(Form)
        self.label_charge2.setGeometry(QtCore.QRect(920, 200, 51, 21))
        self.label_charge2.setObjectName("label_charge2")
        self.line_26 = QtWidgets.QFrame(Form)
        self.line_26.setGeometry(QtCore.QRect(50, 220, 1061, 20))
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.textBrowser_problem3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem3.setGeometry(QtCore.QRect(420, 240, 371, 41))
        self.textBrowser_problem3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem3.setLineWidth(0)
        self.textBrowser_problem3.setObjectName("textBrowser_problem3")
        self.label_method3 = QtWidgets.QLabel(Form)
        self.label_method3.setGeometry(QtCore.QRect(800, 250, 101, 21))
        self.label_method3.setObjectName("label_method3")
        self.label_classify3 = QtWidgets.QLabel(Form)
        self.label_classify3.setGeometry(QtCore.QRect(980, 250, 121, 21))
        self.label_classify3.setObjectName("label_classify3")
        self.label_name3 = QtWidgets.QLabel(Form)
        self.label_name3.setGeometry(QtCore.QRect(160, 250, 251, 21))
        self.label_name3.setObjectName("label_name3")
        self.line_10 = QtWidgets.QFrame(Form)
        self.line_10.setGeometry(QtCore.QRect(50, 230, 1061, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_27 = QtWidgets.QFrame(Form)
        self.line_27.setGeometry(QtCore.QRect(900, 240, 20, 41))
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.label_handlingTime3 = QtWidgets.QLabel(Form)
        self.label_handlingTime3.setGeometry(QtCore.QRect(60, 250, 101, 21))
        self.label_handlingTime3.setObjectName("label_handlingTime3")
        self.line_28 = QtWidgets.QFrame(Form)
        self.line_28.setGeometry(QtCore.QRect(780, 240, 20, 41))
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.line_29 = QtWidgets.QFrame(Form)
        self.line_29.setGeometry(QtCore.QRect(960, 240, 20, 41))
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.line_30 = QtWidgets.QFrame(Form)
        self.line_30.setGeometry(QtCore.QRect(410, 240, 20, 41))
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.line_31 = QtWidgets.QFrame(Form)
        self.line_31.setGeometry(QtCore.QRect(1100, 240, 20, 41))
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.line_32 = QtWidgets.QFrame(Form)
        self.line_32.setGeometry(QtCore.QRect(40, 240, 20, 41))
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.line_33 = QtWidgets.QFrame(Form)
        self.line_33.setGeometry(QtCore.QRect(140, 240, 20, 41))
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.label_charge3 = QtWidgets.QLabel(Form)
        self.label_charge3.setGeometry(QtCore.QRect(920, 250, 51, 21))
        self.label_charge3.setObjectName("label_charge3")
        self.line_34 = QtWidgets.QFrame(Form)
        self.line_34.setGeometry(QtCore.QRect(50, 270, 1061, 20))
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.textBrowser_problem4 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem4.setGeometry(QtCore.QRect(420, 290, 371, 41))
        self.textBrowser_problem4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem4.setLineWidth(0)
        self.textBrowser_problem4.setObjectName("textBrowser_problem4")
        self.label_method4 = QtWidgets.QLabel(Form)
        self.label_method4.setGeometry(QtCore.QRect(800, 300, 101, 21))
        self.label_method4.setObjectName("label_method4")
        self.label_classify4 = QtWidgets.QLabel(Form)
        self.label_classify4.setGeometry(QtCore.QRect(980, 300, 121, 21))
        self.label_classify4.setObjectName("label_classify4")
        self.label_name4 = QtWidgets.QLabel(Form)
        self.label_name4.setGeometry(QtCore.QRect(160, 300, 251, 21))
        self.label_name4.setObjectName("label_name4")
        self.line_35 = QtWidgets.QFrame(Form)
        self.line_35.setGeometry(QtCore.QRect(50, 280, 1061, 20))
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.line_36 = QtWidgets.QFrame(Form)
        self.line_36.setGeometry(QtCore.QRect(900, 290, 20, 41))
        self.line_36.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.label_handlingTime4 = QtWidgets.QLabel(Form)
        self.label_handlingTime4.setGeometry(QtCore.QRect(60, 300, 101, 21))
        self.label_handlingTime4.setObjectName("label_handlingTime4")
        self.line_37 = QtWidgets.QFrame(Form)
        self.line_37.setGeometry(QtCore.QRect(780, 290, 20, 41))
        self.line_37.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.line_38 = QtWidgets.QFrame(Form)
        self.line_38.setGeometry(QtCore.QRect(960, 290, 20, 41))
        self.line_38.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.line_39 = QtWidgets.QFrame(Form)
        self.line_39.setGeometry(QtCore.QRect(410, 290, 20, 41))
        self.line_39.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.line_40 = QtWidgets.QFrame(Form)
        self.line_40.setGeometry(QtCore.QRect(1100, 290, 20, 41))
        self.line_40.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.line_41 = QtWidgets.QFrame(Form)
        self.line_41.setGeometry(QtCore.QRect(40, 290, 20, 41))
        self.line_41.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.line_42 = QtWidgets.QFrame(Form)
        self.line_42.setGeometry(QtCore.QRect(140, 290, 20, 41))
        self.line_42.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.label_charge4 = QtWidgets.QLabel(Form)
        self.label_charge4.setGeometry(QtCore.QRect(920, 300, 51, 21))
        self.label_charge4.setObjectName("label_charge4")
        self.line_43 = QtWidgets.QFrame(Form)
        self.line_43.setGeometry(QtCore.QRect(50, 320, 1061, 20))
        self.line_43.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.textBrowser_problem5 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem5.setGeometry(QtCore.QRect(420, 340, 371, 41))
        self.textBrowser_problem5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem5.setLineWidth(0)
        self.textBrowser_problem5.setObjectName("textBrowser_problem5")
        self.label_method5 = QtWidgets.QLabel(Form)
        self.label_method5.setGeometry(QtCore.QRect(800, 350, 101, 21))
        self.label_method5.setObjectName("label_method5")
        self.label_classify5 = QtWidgets.QLabel(Form)
        self.label_classify5.setGeometry(QtCore.QRect(980, 350, 121, 21))
        self.label_classify5.setObjectName("label_classify5")
        self.label_name5 = QtWidgets.QLabel(Form)
        self.label_name5.setGeometry(QtCore.QRect(160, 350, 251, 21))
        self.label_name5.setObjectName("label_name5")
        self.line_44 = QtWidgets.QFrame(Form)
        self.line_44.setGeometry(QtCore.QRect(50, 330, 1061, 20))
        self.line_44.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.line_45 = QtWidgets.QFrame(Form)
        self.line_45.setGeometry(QtCore.QRect(900, 340, 20, 41))
        self.line_45.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.label_handlingTime5 = QtWidgets.QLabel(Form)
        self.label_handlingTime5.setGeometry(QtCore.QRect(60, 350, 101, 21))
        self.label_handlingTime5.setObjectName("label_handlingTime5")
        self.line_46 = QtWidgets.QFrame(Form)
        self.line_46.setGeometry(QtCore.QRect(780, 340, 20, 41))
        self.line_46.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.line_47 = QtWidgets.QFrame(Form)
        self.line_47.setGeometry(QtCore.QRect(960, 340, 20, 41))
        self.line_47.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_47.setObjectName("line_47")
        self.line_48 = QtWidgets.QFrame(Form)
        self.line_48.setGeometry(QtCore.QRect(410, 340, 20, 41))
        self.line_48.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_48.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_48.setObjectName("line_48")
        self.line_49 = QtWidgets.QFrame(Form)
        self.line_49.setGeometry(QtCore.QRect(1100, 340, 20, 41))
        self.line_49.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.line_50 = QtWidgets.QFrame(Form)
        self.line_50.setGeometry(QtCore.QRect(40, 340, 20, 41))
        self.line_50.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_50.setObjectName("line_50")
        self.line_51 = QtWidgets.QFrame(Form)
        self.line_51.setGeometry(QtCore.QRect(140, 340, 20, 41))
        self.line_51.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_51.setObjectName("line_51")
        self.label_charge5 = QtWidgets.QLabel(Form)
        self.label_charge5.setGeometry(QtCore.QRect(920, 350, 51, 21))
        self.label_charge5.setObjectName("label_charge5")
        self.line_52 = QtWidgets.QFrame(Form)
        self.line_52.setGeometry(QtCore.QRect(50, 370, 1061, 20))
        self.line_52.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_52.setObjectName("line_52")
        self.textBrowser_problem6 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem6.setGeometry(QtCore.QRect(420, 390, 371, 41))
        self.textBrowser_problem6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem6.setLineWidth(0)
        self.textBrowser_problem6.setObjectName("textBrowser_problem6")
        self.label_method6 = QtWidgets.QLabel(Form)
        self.label_method6.setGeometry(QtCore.QRect(800, 400, 101, 21))
        self.label_method6.setObjectName("label_method6")
        self.label_classify6 = QtWidgets.QLabel(Form)
        self.label_classify6.setGeometry(QtCore.QRect(980, 400, 121, 21))
        self.label_classify6.setObjectName("label_classify6")
        self.label_name6 = QtWidgets.QLabel(Form)
        self.label_name6.setGeometry(QtCore.QRect(160, 400, 251, 21))
        self.label_name6.setObjectName("label_name6")
        self.line_53 = QtWidgets.QFrame(Form)
        self.line_53.setGeometry(QtCore.QRect(50, 380, 1061, 20))
        self.line_53.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_53.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_53.setObjectName("line_53")
        self.line_54 = QtWidgets.QFrame(Form)
        self.line_54.setGeometry(QtCore.QRect(900, 390, 20, 41))
        self.line_54.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_54.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_54.setObjectName("line_54")
        self.label_handlingTime6 = QtWidgets.QLabel(Form)
        self.label_handlingTime6.setGeometry(QtCore.QRect(60, 400, 101, 21))
        self.label_handlingTime6.setObjectName("label_handlingTime6")
        self.line_55 = QtWidgets.QFrame(Form)
        self.line_55.setGeometry(QtCore.QRect(780, 390, 20, 41))
        self.line_55.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_55.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_55.setObjectName("line_55")
        self.line_56 = QtWidgets.QFrame(Form)
        self.line_56.setGeometry(QtCore.QRect(960, 390, 20, 41))
        self.line_56.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_56.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_56.setObjectName("line_56")
        self.line_57 = QtWidgets.QFrame(Form)
        self.line_57.setGeometry(QtCore.QRect(410, 390, 20, 41))
        self.line_57.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_57.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_57.setObjectName("line_57")
        self.line_58 = QtWidgets.QFrame(Form)
        self.line_58.setGeometry(QtCore.QRect(1100, 390, 20, 41))
        self.line_58.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_58.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_58.setObjectName("line_58")
        self.line_59 = QtWidgets.QFrame(Form)
        self.line_59.setGeometry(QtCore.QRect(40, 390, 20, 41))
        self.line_59.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_59.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_59.setObjectName("line_59")
        self.line_60 = QtWidgets.QFrame(Form)
        self.line_60.setGeometry(QtCore.QRect(140, 390, 20, 41))
        self.line_60.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_60.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_60.setObjectName("line_60")
        self.label_charge6 = QtWidgets.QLabel(Form)
        self.label_charge6.setGeometry(QtCore.QRect(920, 400, 51, 21))
        self.label_charge6.setObjectName("label_charge6")
        self.line_61 = QtWidgets.QFrame(Form)
        self.line_61.setGeometry(QtCore.QRect(50, 420, 1061, 20))
        self.line_61.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_61.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_61.setObjectName("line_61")
        self.textBrowser_problem7 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem7.setGeometry(QtCore.QRect(420, 440, 371, 41))
        self.textBrowser_problem7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem7.setLineWidth(0)
        self.textBrowser_problem7.setObjectName("textBrowser_problem7")
        self.label_method7 = QtWidgets.QLabel(Form)
        self.label_method7.setGeometry(QtCore.QRect(800, 450, 101, 21))
        self.label_method7.setObjectName("label_method7")
        self.label_classify7 = QtWidgets.QLabel(Form)
        self.label_classify7.setGeometry(QtCore.QRect(980, 450, 121, 21))
        self.label_classify7.setObjectName("label_classify7")
        self.label_name7 = QtWidgets.QLabel(Form)
        self.label_name7.setGeometry(QtCore.QRect(160, 450, 251, 21))
        self.label_name7.setObjectName("label_name7")
        self.line_62 = QtWidgets.QFrame(Form)
        self.line_62.setGeometry(QtCore.QRect(50, 430, 1061, 20))
        self.line_62.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_62.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_62.setObjectName("line_62")
        self.line_63 = QtWidgets.QFrame(Form)
        self.line_63.setGeometry(QtCore.QRect(900, 440, 20, 41))
        self.line_63.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_63.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_63.setObjectName("line_63")
        self.label_handlingTime7 = QtWidgets.QLabel(Form)
        self.label_handlingTime7.setGeometry(QtCore.QRect(60, 450, 101, 21))
        self.label_handlingTime7.setObjectName("label_handlingTime7")
        self.line_64 = QtWidgets.QFrame(Form)
        self.line_64.setGeometry(QtCore.QRect(780, 440, 20, 41))
        self.line_64.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_64.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_64.setObjectName("line_64")
        self.line_65 = QtWidgets.QFrame(Form)
        self.line_65.setGeometry(QtCore.QRect(960, 440, 20, 41))
        self.line_65.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_65.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_65.setObjectName("line_65")
        self.line_66 = QtWidgets.QFrame(Form)
        self.line_66.setGeometry(QtCore.QRect(410, 440, 20, 41))
        self.line_66.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_66.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_66.setObjectName("line_66")
        self.line_67 = QtWidgets.QFrame(Form)
        self.line_67.setGeometry(QtCore.QRect(1100, 440, 20, 41))
        self.line_67.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_67.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_67.setObjectName("line_67")
        self.line_68 = QtWidgets.QFrame(Form)
        self.line_68.setGeometry(QtCore.QRect(40, 440, 20, 41))
        self.line_68.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_68.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_68.setObjectName("line_68")
        self.line_69 = QtWidgets.QFrame(Form)
        self.line_69.setGeometry(QtCore.QRect(140, 440, 20, 41))
        self.line_69.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_69.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_69.setObjectName("line_69")
        self.label_charge7 = QtWidgets.QLabel(Form)
        self.label_charge7.setGeometry(QtCore.QRect(920, 450, 51, 21))
        self.label_charge7.setObjectName("label_charge7")
        self.line_70 = QtWidgets.QFrame(Form)
        self.line_70.setGeometry(QtCore.QRect(50, 470, 1061, 20))
        self.line_70.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_70.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_70.setObjectName("line_70")
        self.textBrowser_problem8 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem8.setGeometry(QtCore.QRect(420, 490, 371, 41))
        self.textBrowser_problem8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem8.setLineWidth(0)
        self.textBrowser_problem8.setObjectName("textBrowser_problem8")
        self.label_method8 = QtWidgets.QLabel(Form)
        self.label_method8.setGeometry(QtCore.QRect(800, 500, 101, 21))
        self.label_method8.setObjectName("label_method8")
        self.label_classify8 = QtWidgets.QLabel(Form)
        self.label_classify8.setGeometry(QtCore.QRect(980, 500, 121, 21))
        self.label_classify8.setObjectName("label_classify8")
        self.label_name8 = QtWidgets.QLabel(Form)
        self.label_name8.setGeometry(QtCore.QRect(160, 500, 251, 21))
        self.label_name8.setObjectName("label_name8")
        self.line_71 = QtWidgets.QFrame(Form)
        self.line_71.setGeometry(QtCore.QRect(50, 480, 1061, 20))
        self.line_71.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_71.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_71.setObjectName("line_71")
        self.line_72 = QtWidgets.QFrame(Form)
        self.line_72.setGeometry(QtCore.QRect(900, 490, 20, 41))
        self.line_72.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_72.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_72.setObjectName("line_72")
        self.label_handlingTime8 = QtWidgets.QLabel(Form)
        self.label_handlingTime8.setGeometry(QtCore.QRect(60, 500, 101, 21))
        self.label_handlingTime8.setObjectName("label_handlingTime8")
        self.line_73 = QtWidgets.QFrame(Form)
        self.line_73.setGeometry(QtCore.QRect(780, 490, 20, 41))
        self.line_73.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_73.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_73.setObjectName("line_73")
        self.line_74 = QtWidgets.QFrame(Form)
        self.line_74.setGeometry(QtCore.QRect(960, 490, 20, 41))
        self.line_74.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_74.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_74.setObjectName("line_74")
        self.line_75 = QtWidgets.QFrame(Form)
        self.line_75.setGeometry(QtCore.QRect(410, 490, 20, 41))
        self.line_75.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_75.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_75.setObjectName("line_75")
        self.line_76 = QtWidgets.QFrame(Form)
        self.line_76.setGeometry(QtCore.QRect(1100, 490, 20, 41))
        self.line_76.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_76.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_76.setObjectName("line_76")
        self.line_77 = QtWidgets.QFrame(Form)
        self.line_77.setGeometry(QtCore.QRect(40, 490, 20, 41))
        self.line_77.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_77.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_77.setObjectName("line_77")
        self.line_78 = QtWidgets.QFrame(Form)
        self.line_78.setGeometry(QtCore.QRect(140, 490, 20, 41))
        self.line_78.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_78.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_78.setObjectName("line_78")
        self.label_charge8 = QtWidgets.QLabel(Form)
        self.label_charge8.setGeometry(QtCore.QRect(920, 500, 51, 21))
        self.label_charge8.setObjectName("label_charge8")
        self.line_79 = QtWidgets.QFrame(Form)
        self.line_79.setGeometry(QtCore.QRect(50, 520, 1061, 20))
        self.line_79.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_79.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_79.setObjectName("line_79")
        self.textBrowser_problem9 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem9.setGeometry(QtCore.QRect(420, 540, 371, 41))
        self.textBrowser_problem9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem9.setLineWidth(0)
        self.textBrowser_problem9.setObjectName("textBrowser_problem9")
        self.label_method9 = QtWidgets.QLabel(Form)
        self.label_method9.setGeometry(QtCore.QRect(800, 550, 101, 21))
        self.label_method9.setObjectName("label_method9")
        self.label_classify9 = QtWidgets.QLabel(Form)
        self.label_classify9.setGeometry(QtCore.QRect(980, 550, 121, 21))
        self.label_classify9.setObjectName("label_classify9")
        self.label_name9 = QtWidgets.QLabel(Form)
        self.label_name9.setGeometry(QtCore.QRect(160, 550, 251, 21))
        self.label_name9.setObjectName("label_name9")
        self.line_80 = QtWidgets.QFrame(Form)
        self.line_80.setGeometry(QtCore.QRect(50, 530, 1061, 20))
        self.line_80.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_80.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_80.setObjectName("line_80")
        self.line_81 = QtWidgets.QFrame(Form)
        self.line_81.setGeometry(QtCore.QRect(900, 540, 20, 41))
        self.line_81.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_81.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_81.setObjectName("line_81")
        self.label_handlingTime9 = QtWidgets.QLabel(Form)
        self.label_handlingTime9.setGeometry(QtCore.QRect(60, 550, 101, 21))
        self.label_handlingTime9.setObjectName("label_handlingTime9")
        self.line_82 = QtWidgets.QFrame(Form)
        self.line_82.setGeometry(QtCore.QRect(780, 540, 20, 41))
        self.line_82.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_82.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_82.setObjectName("line_82")
        self.line_83 = QtWidgets.QFrame(Form)
        self.line_83.setGeometry(QtCore.QRect(960, 540, 20, 41))
        self.line_83.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_83.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_83.setObjectName("line_83")
        self.line_84 = QtWidgets.QFrame(Form)
        self.line_84.setGeometry(QtCore.QRect(410, 540, 20, 41))
        self.line_84.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_84.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_84.setObjectName("line_84")
        self.line_85 = QtWidgets.QFrame(Form)
        self.line_85.setGeometry(QtCore.QRect(1100, 540, 20, 41))
        self.line_85.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_85.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_85.setObjectName("line_85")
        self.line_86 = QtWidgets.QFrame(Form)
        self.line_86.setGeometry(QtCore.QRect(40, 540, 20, 41))
        self.line_86.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_86.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_86.setObjectName("line_86")
        self.line_87 = QtWidgets.QFrame(Form)
        self.line_87.setGeometry(QtCore.QRect(140, 540, 20, 41))
        self.line_87.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_87.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_87.setObjectName("line_87")
        self.label_charge9 = QtWidgets.QLabel(Form)
        self.label_charge9.setGeometry(QtCore.QRect(920, 550, 51, 21))
        self.label_charge9.setObjectName("label_charge9")
        self.line_88 = QtWidgets.QFrame(Form)
        self.line_88.setGeometry(QtCore.QRect(50, 570, 1061, 20))
        self.line_88.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_88.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_88.setObjectName("line_88")
        self.textBrowser_problem10 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_problem10.setGeometry(QtCore.QRect(420, 590, 371, 41))
        self.textBrowser_problem10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_problem10.setLineWidth(0)
        self.textBrowser_problem10.setObjectName("textBrowser_problem10")
        self.label_method10 = QtWidgets.QLabel(Form)
        self.label_method10.setGeometry(QtCore.QRect(800, 600, 101, 21))
        self.label_method10.setObjectName("label_method10")
        self.label_classify10 = QtWidgets.QLabel(Form)
        self.label_classify10.setGeometry(QtCore.QRect(980, 600, 121, 21))
        self.label_classify10.setObjectName("label_classify10")
        self.label_name10 = QtWidgets.QLabel(Form)
        self.label_name10.setGeometry(QtCore.QRect(160, 600, 251, 21))
        self.label_name10.setObjectName("label_name10")
        self.line_89 = QtWidgets.QFrame(Form)
        self.line_89.setGeometry(QtCore.QRect(50, 580, 1061, 20))
        self.line_89.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_89.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_89.setObjectName("line_89")
        self.line_90 = QtWidgets.QFrame(Form)
        self.line_90.setGeometry(QtCore.QRect(900, 590, 20, 41))
        self.line_90.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_90.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_90.setObjectName("line_90")
        self.label_handlingTime10 = QtWidgets.QLabel(Form)
        self.label_handlingTime10.setGeometry(QtCore.QRect(60, 600, 101, 21))
        self.label_handlingTime10.setObjectName("label_handlingTime10")
        self.line_91 = QtWidgets.QFrame(Form)
        self.line_91.setGeometry(QtCore.QRect(780, 590, 20, 41))
        self.line_91.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_91.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_91.setObjectName("line_91")
        self.line_92 = QtWidgets.QFrame(Form)
        self.line_92.setGeometry(QtCore.QRect(960, 590, 20, 41))
        self.line_92.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_92.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_92.setObjectName("line_92")
        self.line_93 = QtWidgets.QFrame(Form)
        self.line_93.setGeometry(QtCore.QRect(410, 590, 20, 41))
        self.line_93.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_93.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_93.setObjectName("line_93")
        self.line_94 = QtWidgets.QFrame(Form)
        self.line_94.setGeometry(QtCore.QRect(1100, 590, 20, 41))
        self.line_94.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_94.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_94.setObjectName("line_94")
        self.line_95 = QtWidgets.QFrame(Form)
        self.line_95.setGeometry(QtCore.QRect(40, 590, 20, 41))
        self.line_95.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_95.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_95.setObjectName("line_95")
        self.line_96 = QtWidgets.QFrame(Form)
        self.line_96.setGeometry(QtCore.QRect(140, 590, 20, 41))
        self.line_96.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_96.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_96.setObjectName("line_96")
        self.label_charge10 = QtWidgets.QLabel(Form)
        self.label_charge10.setGeometry(QtCore.QRect(920, 600, 51, 21))
        self.label_charge10.setObjectName("label_charge10")
        self.line_97 = QtWidgets.QFrame(Form)
        self.line_97.setGeometry(QtCore.QRect(50, 620, 1061, 20))
        self.line_97.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_97.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_97.setObjectName("line_97")
        self.pushButton_edit6 = QtWidgets.QPushButton(Form)
        self.pushButton_edit6.setGeometry(QtCore.QRect(1130, 400, 71, 23))
        self.pushButton_edit6.setObjectName("pushButton_edit6")
        self.pushButton_edit10 = QtWidgets.QPushButton(Form)
        self.pushButton_edit10.setGeometry(QtCore.QRect(1130, 600, 71, 23))
        self.pushButton_edit10.setObjectName("pushButton_edit10")
        self.pushButton_edit7 = QtWidgets.QPushButton(Form)
        self.pushButton_edit7.setGeometry(QtCore.QRect(1130, 450, 71, 23))
        self.pushButton_edit7.setObjectName("pushButton_edit7")
        self.pushButton_edit4 = QtWidgets.QPushButton(Form)
        self.pushButton_edit4.setGeometry(QtCore.QRect(1130, 300, 71, 23))
        self.pushButton_edit4.setObjectName("pushButton_edit4")
        self.pushButton_edit5 = QtWidgets.QPushButton(Form)
        self.pushButton_edit5.setGeometry(QtCore.QRect(1130, 350, 71, 23))
        self.pushButton_edit5.setObjectName("pushButton_edit5")
        self.pushButton_edit1 = QtWidgets.QPushButton(Form)
        self.pushButton_edit1.setGeometry(QtCore.QRect(1130, 150, 71, 23))
        self.pushButton_edit1.setObjectName("pushButton_edit1")
        self.pushButton_edit9 = QtWidgets.QPushButton(Form)
        self.pushButton_edit9.setGeometry(QtCore.QRect(1130, 550, 71, 23))
        self.pushButton_edit9.setObjectName("pushButton_edit9")
        self.pushButton_edit2 = QtWidgets.QPushButton(Form)
        self.pushButton_edit2.setGeometry(QtCore.QRect(1130, 200, 71, 23))
        self.pushButton_edit2.setObjectName("pushButton_edit2")
        self.pushButton_edit3 = QtWidgets.QPushButton(Form)
        self.pushButton_edit3.setGeometry(QtCore.QRect(1130, 250, 71, 23))
        self.pushButton_edit3.setObjectName("pushButton_edit3")
        self.pushButton_edit8 = QtWidgets.QPushButton(Form)
        self.pushButton_edit8.setGeometry(QtCore.QRect(1130, 500, 71, 23))
        self.pushButton_edit8.setObjectName("pushButton_edit8")
        self.label_id6 = QtWidgets.QLabel(Form)
        self.label_id6.setGeometry(QtCore.QRect(1120, 430, 71, 21))
        self.label_id6.setText("")
        self.label_id6.setObjectName("label_id6")
        self.label_id2 = QtWidgets.QLabel(Form)
        self.label_id2.setGeometry(QtCore.QRect(1120, 230, 71, 21))
        self.label_id2.setText("")
        self.label_id2.setObjectName("label_id2")
        self.label_id5 = QtWidgets.QLabel(Form)
        self.label_id5.setGeometry(QtCore.QRect(1120, 380, 71, 21))
        self.label_id5.setText("")
        self.label_id5.setObjectName("label_id5")
        self.label_id4 = QtWidgets.QLabel(Form)
        self.label_id4.setGeometry(QtCore.QRect(1120, 330, 71, 21))
        self.label_id4.setText("")
        self.label_id4.setObjectName("label_id4")
        self.label_id9 = QtWidgets.QLabel(Form)
        self.label_id9.setGeometry(QtCore.QRect(1120, 580, 71, 21))
        self.label_id9.setText("")
        self.label_id9.setObjectName("label_id9")
        self.label_id7 = QtWidgets.QLabel(Form)
        self.label_id7.setGeometry(QtCore.QRect(1120, 480, 71, 21))
        self.label_id7.setText("")
        self.label_id7.setObjectName("label_id7")
        self.label_id10 = QtWidgets.QLabel(Form)
        self.label_id10.setGeometry(QtCore.QRect(1120, 630, 71, 21))
        self.label_id10.setText("")
        self.label_id10.setObjectName("label_id10")
        self.label_id1 = QtWidgets.QLabel(Form)
        self.label_id1.setGeometry(QtCore.QRect(1120, 180, 71, 21))
        self.label_id1.setText("")
        self.label_id1.setObjectName("label_id1")
        self.label_id3 = QtWidgets.QLabel(Form)
        self.label_id3.setGeometry(QtCore.QRect(1120, 280, 71, 21))
        self.label_id3.setText("")
        self.label_id3.setObjectName("label_id3")
        self.label_id8 = QtWidgets.QLabel(Form)
        self.label_id8.setGeometry(QtCore.QRect(1120, 530, 71, 21))
        self.label_id8.setText("")
        self.label_id8.setObjectName("label_id8")
        self.label_13.raise_()
        self.lineEdit_search.raise_()
        self.label_name1.raise_()
        self.line_7.raise_()
        self.pushButton_SwitchCustomer.raise_()
        self.label_4.raise_()
        self.pushButton_SwitchService.raise_()
        self.label_8.raise_()
        self.label_5.raise_()
        self.pushButton_previous.raise_()
        self.pushButton_next.raise_()
        self.pushButton_new.raise_()
        self.pushButton_jump.raise_()
        self.label_9.raise_()
        self.lineEdit_jump.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_17.raise_()
        self.line_11.raise_()
        self.pushButton_search.raise_()
        self.pushButton_SwitchShipment.raise_()
        self.label_22.raise_()
        self.label_cPage.raise_()
        self.label_tPage.raise_()
        self.label_order1.raise_()
        self.line_8.raise_()
        self.line_12.raise_()
        self.line_13.raise_()
        self.line_14.raise_()
        self.line_15.raise_()
        self.line_16.raise_()
        self.line_22.raise_()
        self.label_order2.raise_()
        self.label_order3.raise_()
        self.label_order4.raise_()
        self.label_order5.raise_()
        self.label_order6.raise_()
        self.label_order7.raise_()
        self.label_order8.raise_()
        self.label_order9.raise_()
        self.label_order10.raise_()
        self.pushButton_advSearch.raise_()
        self.line_149.raise_()
        self.line_150.raise_()
        self.pushButton_ProblemSource.raise_()
        self.line_23.raise_()
        self.label_18.raise_()
        self.textBrowser_problem1.raise_()
        self.label_handlingTime1.raise_()
        self.label_method1.raise_()
        self.label_charge1.raise_()
        self.label_classify1.raise_()
        self.textBrowser_problem2.raise_()
        self.label_method2.raise_()
        self.label_classify2.raise_()
        self.label_name2.raise_()
        self.line_9.raise_()
        self.line_17.raise_()
        self.label_handlingTime2.raise_()
        self.line_18.raise_()
        self.line_24.raise_()
        self.line_19.raise_()
        self.line_25.raise_()
        self.line_20.raise_()
        self.line_21.raise_()
        self.label_charge2.raise_()
        self.line_26.raise_()
        self.textBrowser_problem3.raise_()
        self.label_method3.raise_()
        self.label_classify3.raise_()
        self.label_name3.raise_()
        self.line_10.raise_()
        self.line_27.raise_()
        self.label_handlingTime3.raise_()
        self.line_28.raise_()
        self.line_29.raise_()
        self.line_30.raise_()
        self.line_31.raise_()
        self.line_32.raise_()
        self.line_33.raise_()
        self.label_charge3.raise_()
        self.line_34.raise_()
        self.textBrowser_problem4.raise_()
        self.label_method4.raise_()
        self.label_classify4.raise_()
        self.label_name4.raise_()
        self.line_35.raise_()
        self.line_36.raise_()
        self.label_handlingTime4.raise_()
        self.line_37.raise_()
        self.line_38.raise_()
        self.line_39.raise_()
        self.line_40.raise_()
        self.line_41.raise_()
        self.line_42.raise_()
        self.label_charge4.raise_()
        self.line_43.raise_()
        self.textBrowser_problem5.raise_()
        self.label_method5.raise_()
        self.label_classify5.raise_()
        self.label_name5.raise_()
        self.line_44.raise_()
        self.line_45.raise_()
        self.label_handlingTime5.raise_()
        self.line_46.raise_()
        self.line_47.raise_()
        self.line_48.raise_()
        self.line_49.raise_()
        self.line_50.raise_()
        self.line_51.raise_()
        self.label_charge5.raise_()
        self.line_52.raise_()
        self.textBrowser_problem6.raise_()
        self.label_method6.raise_()
        self.label_classify6.raise_()
        self.label_name6.raise_()
        self.line_53.raise_()
        self.line_54.raise_()
        self.label_handlingTime6.raise_()
        self.line_55.raise_()
        self.line_56.raise_()
        self.line_57.raise_()
        self.line_58.raise_()
        self.line_59.raise_()
        self.line_60.raise_()
        self.label_charge6.raise_()
        self.line_61.raise_()
        self.textBrowser_problem7.raise_()
        self.label_method7.raise_()
        self.label_classify7.raise_()
        self.label_name7.raise_()
        self.line_62.raise_()
        self.line_63.raise_()
        self.label_handlingTime7.raise_()
        self.line_64.raise_()
        self.line_65.raise_()
        self.line_66.raise_()
        self.line_67.raise_()
        self.line_68.raise_()
        self.line_69.raise_()
        self.label_charge7.raise_()
        self.line_70.raise_()
        self.textBrowser_problem8.raise_()
        self.label_method8.raise_()
        self.label_classify8.raise_()
        self.label_name8.raise_()
        self.line_71.raise_()
        self.line_72.raise_()
        self.label_handlingTime8.raise_()
        self.line_73.raise_()
        self.line_74.raise_()
        self.line_75.raise_()
        self.line_76.raise_()
        self.line_77.raise_()
        self.line_78.raise_()
        self.label_charge8.raise_()
        self.line_79.raise_()
        self.textBrowser_problem9.raise_()
        self.label_method9.raise_()
        self.label_classify9.raise_()
        self.label_name9.raise_()
        self.line_80.raise_()
        self.line_81.raise_()
        self.label_handlingTime9.raise_()
        self.line_82.raise_()
        self.line_83.raise_()
        self.line_84.raise_()
        self.line_85.raise_()
        self.line_86.raise_()
        self.line_87.raise_()
        self.label_charge9.raise_()
        self.line_88.raise_()
        self.textBrowser_problem10.raise_()
        self.label_method10.raise_()
        self.label_classify10.raise_()
        self.label_name10.raise_()
        self.line_89.raise_()
        self.line_90.raise_()
        self.label_handlingTime10.raise_()
        self.line_91.raise_()
        self.line_92.raise_()
        self.line_93.raise_()
        self.line_94.raise_()
        self.line_95.raise_()
        self.line_96.raise_()
        self.label_charge10.raise_()
        self.line_97.raise_()
        self.pushButton_edit6.raise_()
        self.pushButton_edit10.raise_()
        self.pushButton_edit7.raise_()
        self.pushButton_edit4.raise_()
        self.pushButton_edit5.raise_()
        self.pushButton_edit1.raise_()
        self.pushButton_edit9.raise_()
        self.pushButton_edit2.raise_()
        self.pushButton_edit3.raise_()
        self.pushButton_edit8.raise_()
        self.label_id6.raise_()
        self.label_id2.raise_()
        self.label_id5.raise_()
        self.label_id4.raise_()
        self.label_id9.raise_()
        self.label_id7.raise_()
        self.label_id10.raise_()
        self.label_id1.raise_()
        self.label_id3.raise_()
        self.label_id8.raise_()

        self.retranslateUi(Form)
        self.pushButton_previous.clicked.connect(Form.reloadWidgetDec)
        self.pushButton_next.clicked.connect(Form.reloadWidgetAdd)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#0b3da8;\">售后服务信息</span></p></body></html>"))
        self.label_name1.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#000000;\">customer</span></p></body></html>"))
        self.pushButton_SwitchCustomer.setText(_translate("Form", "客户信息界面"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">反馈问题</span></p></body></html>"))
        self.pushButton_SwitchService.setText(_translate("Form", "售后服务记录"))
        self.label_8.setText(_translate("Form", "搜索"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">处理方式</span></p></body></html>"))
        self.pushButton_previous.setText(_translate("Form", "上一页"))
        self.pushButton_next.setText(_translate("Form", "下一页"))
        self.pushButton_new.setText(_translate("Form", "新增客户信息"))
        self.pushButton_jump.setText(_translate("Form", "GO!"))
        self.label_9.setText(_translate("Form", "跳到第       页"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">客户名称</span></p></body></html>"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">处理时间</span></p></body></html>"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">收费金额</span></p></body></html>"))
        self.pushButton_search.setText(_translate("Form", "GO!"))
        self.pushButton_SwitchShipment.setText(_translate("Form", "产品出货信息"))
        self.label_22.setText(_translate("Form", "第        /         页"))
        self.label_cPage.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#063661;\">cPage</span></p></body></html>"))
        self.label_tPage.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#063661;\">tPage</span></p></body></html>"))
        self.label_order1.setText(_translate("Form", "order"))
        self.label_order2.setText(_translate("Form", "order"))
        self.label_order3.setText(_translate("Form", "order"))
        self.label_order4.setText(_translate("Form", "order"))
        self.label_order5.setText(_translate("Form", "order"))
        self.label_order6.setText(_translate("Form", "order"))
        self.label_order7.setText(_translate("Form", "order"))
        self.label_order8.setText(_translate("Form", "order"))
        self.label_order9.setText(_translate("Form", "order"))
        self.label_order10.setText(_translate("Form", "order"))
        self.pushButton_advSearch.setText(_translate("Form", "显示全部内容"))
        self.pushButton_ProblemSource.setText(_translate("Form", "分类统计"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">问题归类</span></p></body></html>"))
        self.textBrowser_problem1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_handlingTime1.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_method1.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.label_charge1.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.label_classify1.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.textBrowser_problem2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_method2.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.label_classify2.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.label_name2.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#000000;\">customer</span></p></body></html>"))
        self.label_handlingTime2.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_charge2.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.textBrowser_problem3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_method3.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.label_classify3.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.label_name3.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#000000;\">customer</span></p></body></html>"))
        self.label_handlingTime3.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_charge3.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.textBrowser_problem4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_method4.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.label_classify4.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.label_name4.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#000000;\">customer</span></p></body></html>"))
        self.label_handlingTime4.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_charge4.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.textBrowser_problem5.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_method5.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.label_classify5.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.label_name5.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#000000;\">customer</span></p></body></html>"))
        self.label_handlingTime5.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_charge5.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.textBrowser_problem6.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_method6.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.label_classify6.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.label_name6.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#000000;\">customer</span></p></body></html>"))
        self.label_handlingTime6.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_charge6.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.textBrowser_problem7.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_method7.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.label_classify7.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.label_name7.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#000000;\">customer</span></p></body></html>"))
        self.label_handlingTime7.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_charge7.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.textBrowser_problem8.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_method8.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.label_classify8.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.label_name8.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#000000;\">customer</span></p></body></html>"))
        self.label_handlingTime8.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_charge8.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.textBrowser_problem9.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_method9.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.label_classify9.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.label_name9.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#000000;\">customer</span></p></body></html>"))
        self.label_handlingTime9.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_charge9.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.textBrowser_problem10.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problem</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_method10.setText(_translate("Form", "<html><head/><body><p>method</p></body></html>"))
        self.label_classify10.setText(_translate("Form", "<html><head/><body><p>classify</p></body></html>"))
        self.label_name10.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#000000;\">customer</span></p></body></html>"))
        self.label_handlingTime10.setText(_translate("Form", "<html><head/><body><p>handlingTime</p></body></html>"))
        self.label_charge10.setText(_translate("Form", "<html><head/><body><p>charge</p></body></html>"))
        self.pushButton_edit6.setText(_translate("Form", "详细信息"))
        self.pushButton_edit10.setText(_translate("Form", "详细信息"))
        self.pushButton_edit7.setText(_translate("Form", "详细信息"))
        self.pushButton_edit4.setText(_translate("Form", "详细信息"))
        self.pushButton_edit5.setText(_translate("Form", "详细信息"))
        self.pushButton_edit1.setText(_translate("Form", "详细信息"))
        self.pushButton_edit9.setText(_translate("Form", "详细信息"))
        self.pushButton_edit2.setText(_translate("Form", "详细信息"))
        self.pushButton_edit3.setText(_translate("Form", "详细信息"))
        self.pushButton_edit8.setText(_translate("Form", "详细信息"))

####以上为QTDesiger自动生成代码
###以下为自己写的代码
    def closeEvent(self, event):        #关闭窗口触发以下事件
        reply = QMessageBox.question(self, '消息提示', '你确定要退出吗?', QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
        if reply == QMessageBox.Yes:
            event.accept()        #接受关闭事件
        else:
            event.ignore()        #忽略关闭事件
    def reloadWidgetAdd(self): #点击下一页触发
        global databaseFlag         #以下查看databaseFlag以判断当前使用的是哪个数据库。
        if databaseFlag==0:
            data=self.database() #如果m=0，则显示全部数据库内容
        elif databaseFlag==1:
            data=self.rdatabase()#如果m=1，则按问题分类列表显示
        else:
            data=self.sdatabase()#如果都不是，则读取搜索数据库内容
        i= int(self.label_order10.text())
        j=len(self.database()) #数据库的总记录条数=j
        if i < j:
            global g
            g+=1 #全局变量P页数+1
            if databaseFlag==0:
                self.pageDisplay(0,g)
            elif databaseFlag==1:
                self.pageDisplay(1,g)
            else:
                self.pageDisplay(2,g)
        else:
            print("remain")
    def reloadWidgetDec(self): #点击上一页触发
        global databaseFlag
        i= int(self.label_order10.text())
        if i > 10:
            global g
            g-=1 #全局变量P页数-1
            if databaseFlag==0:
                self.pageDisplay(0,g)
            elif databaseFlag==1:
                self.pageDisplay(1,g)
            else:
                self.pageDisplay(2,g)
        else:
            print("remain")

    def pageDisplay(self,m,g):  #本函数显示g页的数据
        print("service_browser:pageDisplay",g)
        global databaseFlag
        databaseFlag=m
        print("databaseFlag=",databaseFlag)
        if m==0:
            data=self.database() #如果m=0，则显示全部数据库内容
        elif m==1:
            data=self.rdatabase()#如果m=1，则显示应收款客户列表
        else:
            data=self.sdatabase()#如果都不是，则读取搜索数据库内容

        self.pushButton_edit2.show() #显示开始，先把之前可能隐藏的按钮重新显示出来
        self.pushButton_edit3.show()
        self.pushButton_edit4.show()
        self.pushButton_edit5.show()
        self.pushButton_edit6.show()
        self.pushButton_edit7.show()
        self.pushButton_edit8.show()
        self.pushButton_edit9.show()
        self.pushButton_edit10.show()

        orderJ=g*10
        orderI=orderJ-1
        orderH=orderJ-2
        orderG=orderJ-3
        orderF=orderJ-4
        orderE=orderJ-5
        orderD=orderJ-6
        orderC=orderJ-7
        orderB=orderJ-8
        orderA=orderJ-9
        self.label_order1.setText(str(orderA))
        self.label_order2.setText(str(orderB))
        self.label_order3.setText(str(orderC))
        self.label_order4.setText(str(orderD))
        self.label_order5.setText(str(orderE))
        self.label_order6.setText(str(orderF))
        self.label_order7.setText(str(orderG))
        self.label_order8.setText(str(orderH))
        self.label_order9.setText(str(orderI))
        self.label_order10.setText(str(orderJ))

        dblen=len(data)
        p=g*10-9  #获得当前页面的第1行
        blank=["","","","","","","","","",""]
        print("service_browser-pageDisplay:现在数据库中共有记录：",dblen)
        a=dblen%10 #计算最后一页总共有几行？
        b=10-a  #计算空白的有几行
        while b>0:#将当前页面的空白记录行填充N/A，以免data赋值的时候不够5行导致出错
            data.append(blank)
            if g == dblen//10+1:  #如果当前页面是最后一页---总页数/10然后+1
                if b==1: #如果只有1行空白
                    self.pushButton_edit10.hide() #隐藏最后一个编辑按钮
                elif b==2:#如果有2行空白
                    self.pushButton_edit9.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit10.hide()
                elif b==3:#如果有3行空白
                    self.pushButton_edit8.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit9.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit10.hide()
                elif b==4:#如果有4行空白
                    self.pushButton_edit7.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit8.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit9.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit10.hide()
                elif b==5:#如果有5行空白
                    self.pushButton_edit6.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit7.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit8.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit9.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit10.hide()
                elif b==6:#如果有6行空白
                    self.pushButton_edit5.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit6.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit7.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit8.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit9.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit10.hide()
                elif b==7:#如果有7行空白
                    self.pushButton_edit4.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit5.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit6.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit7.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit8.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit9.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit10.hide()
                elif b==8:#如果有8行空白
                    self.pushButton_edit3.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit4.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit5.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit6.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit7.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit8.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit9.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit10.hide()
                elif b==9:#如果有9行空白
                    self.pushButton_edit2.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit3.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit4.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit5.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit6.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit7.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit8.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit9.hide() #隐藏最后2个编辑按钮
                    self.pushButton_edit10.hide()
            b=b-1


#以下将数据库中获取的内容分别对应显示在5行内
        self.label_id1.setText(str(data[p-1][0])) #数据库是从0开始的，所以减1
        self.label_name1.setText(str(data[p-1][1]))
        self.textBrowser_problem1.setText(str(data[p-1][2]))
        self.label_method1.setText(str(data[p-1][3]))
        self.label_handlingTime1.setText(str(data[p-1][4]))
#        self.label_staff1.setText(str(data[p-1][5]))
#        self.textBrowser_solution1.setText(str(data[p-1][6]))
        self.label_charge1.setText(str(data[p-1][7]))
        self.label_classify1.setText(str(data[p-1][8]))
#        self.textBrowser_remark1.setText(str(data[p-1][9]))

        self.label_id2.setText(str(data[p][0]))
        self.label_name2.setText(str(data[p][1]))
        self.textBrowser_problem2.setText(str(data[p][2]))
        self.label_method2.setText(str(data[p][3]))
        self.label_handlingTime2.setText(str(data[p][4]))
#        self.label_staff2.setText(str(data[p][5]))
#        self.textBrowser_solution2.setText(str(data[p][6]))
        self.label_charge2.setText(str(data[p][7]))
        self.label_classify2.setText(str(data[p][8]))
#        self.textBrowser_remark2.setText(str(data[p][9]))

        self.label_id3.setText(str(data[p+1][0]))
        self.label_name3.setText(str(data[p+1][1]))
        self.textBrowser_problem3.setText(str(data[p+1][2]))
        self.label_method3.setText(str(data[p+1][3]))
        self.label_handlingTime3.setText(str(data[p+1][4]))
#        self.label_staff3.setText(str(data[p+1][5]))
#        self.textBrowser_solution3.setText(str(data[p+1][6]))
        self.label_charge3.setText(str(data[p+1][7]))
        self.label_classify3.setText(str(data[p+1][8]))
#        self.textBrowser_remark3.setText(str(data[p+1][9]))

        self.label_id4.setText(str(data[p+2][0]))
        self.label_name4.setText(str(data[p+2][1]))
        self.textBrowser_problem4.setText(str(data[p+2][2]))
        self.label_method4.setText(str(data[p+2][3]))
        self.label_handlingTime4.setText(str(data[p+2][4]))
#        self.label_staff4.setText(str(data[p+2][5]))
#        self.textBrowser_solution4.setText(str(data[p+2][6]))
        self.label_charge4.setText(str(data[p+2][7]))
        self.label_classify4.setText(str(data[p+2][8]))
#        self.textBrowser_remark4.setText(str(data[p+2][9]))

        self.label_id5.setText(str(data[p+3][0]))
        self.label_name5.setText(str(data[p+3][1]))
        self.textBrowser_problem5.setText(str(data[p+3][2]))
        self.label_method5.setText(str(data[p+3][3]))
        self.label_handlingTime5.setText(str(data[p+3][4]))
#        self.label_staff5.setText(str(data[p+3][5]))
#        self.textBrowser_solution5.setText(str(data[p+3][6]))
        self.label_charge5.setText(str(data[p+3][7]))
        self.label_classify5.setText(str(data[p+3][8]))
#        self.textBrowser_remark5.setText(str(data[p+3][9]))

        self.label_id6.setText(str(data[p+4][0]))
        self.label_name6.setText(str(data[p+4][1]))
        self.textBrowser_problem6.setText(str(data[p+4][2]))
        self.label_method6.setText(str(data[p+4][3]))
        self.label_handlingTime6.setText(str(data[p+4][4]))
        self.label_charge6.setText(str(data[p+4][7]))
        self.label_classify6.setText(str(data[p+4][8]))

        self.label_id7.setText(str(data[p+5][0]))
        self.label_name7.setText(str(data[p+5][1]))
        self.textBrowser_problem7.setText(str(data[p+5][2]))
        self.label_method7.setText(str(data[p+5][3]))
        self.label_handlingTime7.setText(str(data[p+5][4]))
        self.label_charge7.setText(str(data[p+5][7]))
        self.label_classify7.setText(str(data[p+5][8]))

        self.label_id8.setText(str(data[p+6][0]))
        self.label_name8.setText(str(data[p+6][1]))
        self.textBrowser_problem8.setText(str(data[p+6][2]))
        self.label_method8.setText(str(data[p+6][3]))
        self.label_handlingTime8.setText(str(data[p+6][4]))
        self.label_charge8.setText(str(data[p+6][7]))
        self.label_classify8.setText(str(data[p+6][8]))

        self.label_id9.setText(str(data[p+7][0]))
        self.label_name9.setText(str(data[p+7][1]))
        self.textBrowser_problem9.setText(str(data[p+7][2]))
        self.label_method9.setText(str(data[p+7][3]))
        self.label_handlingTime9.setText(str(data[p+7][4]))
        self.label_charge9.setText(str(data[p+7][7]))
        self.label_classify9.setText(str(data[p+7][8]))

        self.label_id10.setText(str(data[p+8][0]))
        self.label_name10.setText(str(data[p+8][1]))
        self.textBrowser_problem10.setText(str(data[p+8][2]))
        self.label_method10.setText(str(data[p+8][3]))
        self.label_handlingTime10.setText(str(data[p+8][4]))
        self.label_charge10.setText(str(data[p+8][7]))
        self.label_classify10.setText(str(data[p+8][8]))

        self.label_id1.hide()
        self.label_id2.hide()
        self.label_id3.hide()
        self.label_id4.hide()
        self.label_id5.hide()
        self.label_id6.hide()
        self.label_id7.hide()
        self.label_id8.hide()
        self.label_id9.hide()
        self.label_id10.hide()

# 以下设置页面中的当前页/总页数
        self.label_cPage.setText(str(g))
        if dblen%10==0: #如果能被5整除，就说明总记录刚好是5的倍数
            tPage=int(dblen/10)
        else:
            tPage=int(dblen/10+1) #否则，就应该加1页
        self.label_tPage.setText(str(tPage))

    def reload(self):
        print("browser:reload start")
        global g
        self.pageDisplay(0,g)
        print("browser:reload finish")

    def database(self):
        print("opening database...")
        conn = sqlite3.connect('nextai.db')
        curs = conn.cursor()  #创建游标
        curs.execute("SELECT * from service ORDER BY handlingTime DESC;") # order by按shipDate排序，DESC：逆序
        data= curs.fetchall() #将数据库全部内容读入data中
        curs.close()  #关闭游标
#        conn.commit() #保存数据库
        conn.close() #关闭数据库连接
        return data
    def rdatabase(self):
        print("opening service classify database...")
        #逐个classify类型读取数据库，重新组合放入data中
        data = []
        conn = sqlite3.connect('nextai.db')
        curs = conn.cursor()  #创建游标
        curs.execute("SELECT * from service WHERE classify='（未选择）';")
        dataTem = curs.fetchone() #data[]数组获得数据库中的全部数据
        while dataTem !=None:
            data.append(dataTem)
            dataTem= curs.fetchone()
        curs.execute("SELECT * from service WHERE classify='装配问题';")
        dataTem = curs.fetchone()
        while dataTem !=None:
            data.append(dataTem)
            dataTem= curs.fetchone()
        curs.execute("SELECT * from service WHERE classify='零件质量问题';")
        dataTem = curs.fetchone()
        while dataTem !=None:
            data.append(dataTem)
            dataTem= curs.fetchone()
        curs.execute("SELECT * from service WHERE classify='产品设计问题';")
        dataTem = curs.fetchone()
        while dataTem !=None:
            data.append(dataTem)
            dataTem= curs.fetchone()
        curs.execute("SELECT * from service WHERE classify='使用不当';")
        dataTem = curs.fetchone()
        while dataTem !=None:
            data.append(dataTem)
            dataTem= curs.fetchone()
        curs.execute("SELECT * from service WHERE classify='其他类型';")
        dataTem = curs.fetchone()
        while dataTem !=None:
            data.append(dataTem)
            dataTem= curs.fetchone()
        curs.close()  #关闭游标
        conn.close() #关闭数据库连接
        return data
    def sdatabase(self):
        print("opening search database...")
        kword= str(self.lineEdit_search.text())
        #连接数据库进行模糊查询
        conn = sqlite3.connect('nextai.db')
        curs = conn.cursor()  #创建游标
        sql="SELECT * from service WHERE customer LIKE"+" "+"\'%"+kword+"%\'"
        curs.execute(sql) #sql语句只能为字符串，所以在上一行将sql的字符串添加整齐
        data= curs.fetchall() #data[]数组获得数据库中的全部数据
        curs.close()  #关闭游标
        conn.close() #关闭数据库连接
        return data

    def jumpTo(self):
        jump_g=str(self.lineEdit_jump.text())
        print("jump start")
        if jump_g=="":
            QMessageBox.critical(self,"注意","输入错误，请输入要跳转到的页码，格式为数字")
            pass
        elif jump_g.isdigit()==False:
            QMessageBox.critical(self,"注意","输入错误，请输入要跳转到的页码，格式为数字")
            pass
        else:
            ttPage=int(self.label_tPage.text())
            jump_gg = int(jump_g)
            if jump_gg > ttPage :
                QMessageBox.critical(self,"注意","输入错误，输入的数字超过最大页码了啊！")
            else:
                self.pageDisplay(0,jump_gg)
    def searchDisplay(self):
        kword= str(self.lineEdit_search.text())
        if kword=="": #如果输入的搜索项为空，则reload页面，显示全部信息
            self.reload()
        else:
            self.pageDisplay(2,1)
    def classifyView(self):
        self.pageDisplay(1,1)


class MyForm ( QWidget, Ui_Form ):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.pushButton_jump.clicked.connect(self.jumpTo)
        self.pushButton_search.clicked.connect(self.searchDisplay)
        self.pushButton_advSearch.clicked.connect(self.reload)
        self.pushButton_ProblemSource.clicked.connect(self.classifyView)


global g # 设定当前页面全局变量 g
g=1
global databaseFlag # 设定当前页面全局变量 g
databaseFlag=0

if __name__=='__main__':
    g=1
    app=QApplication(sys.argv)
    w = MyForm()
    w.pageDisplay(0,g)
    w.show()
    a = service_edit.MyForm()
    w.pushButton_edit1.clicked.connect(a.handle_click1)
    w.pushButton_edit2.clicked.connect(a.handle_click2)
    w.pushButton_edit3.clicked.connect(a.handle_click3)
    w.pushButton_edit4.clicked.connect(a.handle_click4)
    w.pushButton_edit5.clicked.connect(a.handle_click5)
    w.pushButton_edit6.clicked.connect(a.handle_click6)
    w.pushButton_edit7.clicked.connect(a.handle_click7)
    w.pushButton_edit8.clicked.connect(a.handle_click8)
    w.pushButton_edit9.clicked.connect(a.handle_click9)
    w.pushButton_edit10.clicked.connect(a.handle_click10)


    app.exec_()



"""
UIC之后，将以下2个语句中的Main修改为self即可
self.pushButton_next.clicked.connect(self.reloadWidgetAdd)
self.pushButton_previous.clicked.connect(self.reloadWidgetDec)

"""
